/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// Agent Chat — Type definitions (ported from saros-webui)

import { AgentStatus } from '../../common/agentStudioTypes.js';
// ★ 2026-09-22（用户选定方案 C「收纳手风琴」）：压缩分组的**纯函数核心**在 contrib/common ✓
//   （与 historyCompaction 同目录 ⇒ 判据唯一真源 ✓；本目录已有 contrib/common import 先例 ✓）
import { planCompactionGroup, type ICompactionGroupMeta, type ICompactionGroupOptions } from '../../contrib/agentStudio/common/compactionGroupPlan.js';

/** Chat message with streaming/tool-call/thinking support */
export interface IAgentChatMessage {
	readonly id: string;
	readonly role: 'user' | 'assistant' | 'system';
	content: string;
	readonly timestamp: number;
	isStreaming?: boolean;
	/** Precise stream phase (replaces boolean isStreaming for UI display) */
	streamPhase?: StreamPhase;
	/**
	 * 瞬时活动文本（2026-07-26）：tool_progress 等轻量进度信号驱动，
	 * 显示在阶段指示器中（如「正在生成工具调用参数… 已 N KB」）。
	 * 仅流式期间有效，tool_start/done 时清除；不参与持久化语义。
	 */
	activityText?: string;
	/** Hermes turn id — shared by multiple assistant messages from same user request, used for aggregation */
	turnId?: string;
	toolCalls?: IToolCall[];
	/**
	 * 阶段E：有序内容片段（text|tool）。存在时作为渲染唯一真相，
	 * 按数组顺序遍历，取代 textPosition 交织。content/toolCalls 仍保留为派生兼容字段。
	 */
	parts?: IMessagePart[];
	thinking?: string;
	isThinking?: boolean;
	currentStep?: string;           // 'call_llm' | 'execute_tool' | custom
	tokenUsage?: {
		input: number;
		output: number;
		total: number;
		/**
		 * ★ 2026-09-21：**最近一次请求**的 prompt 大小（= 当前上下文占用），**不含**本轮历史轮次的累加。
		 *
		 * 为什么需要它：`input` 的语义是「本 turn 全程消费」（多轮 agent loop 下每轮 LLM 调用各发一次
		 * usage delta，此处按轮累加 —— 供 footer 展示总消耗）。而上下文环需要的是「当前 prompt 多大」。
		 * 两者此前共用 `input` ⇒ 长 turn（20+ 轮迭代）后环暴涨（实测 1,465,040 vs 真实 prompt ~80,724），
		 * 显示 100% 却永不触发压缩（压缩判定用 ContextManager 的 real usage，一直远低于 140k 线）。
		 */
		promptTokens?: number;
		/** KV Cache: tokens read from prompt cache (缓存命中). */
		cached?: number;
		/** KV Cache: tokens written to cache (缓存写入). */
		cacheWrite?: number;
		/** Tokens read from prompt cache (缓存命中, same as cached but explicit). */
		cachedRead?: number;
		/** Tokens NOT in cache that had to be processed fresh (缓存未命中). Computed if not provided. */
		cacheMiss?: number;
		/** Reasoning/thinking tokens (思考过程). */
		reasoning?: number;
		/** Cache hit rate as percentage, e.g. 51.6 for 51.6% (缓存命中率). */
		cacheHitRate?: number;
		/** Billing credits consumed by this turn (积分). */
		credit?: number;
		/** 本次 token 消耗对应的 provider（与本回合 LLM 调用一致；多轮时取最新一轮） */
		providerId?: string;
		/** 本次 token 消耗对应的 modelId（同上；用于 Token 消耗明细面板展示） */
		model?: string;
	};
	metadata?: Record<string, unknown>;
	/**
	 * ★ 2026-09-22（用户选定方案 C「收纳手风琴」）：压缩分组元信息。
	 * **存在即代表本条是合成出来的分组消息**（不是真实历史消息 ✓），
	 * 由 `coalesceCompactionGroups` 在有**可信**压缩边界时产出；
	 * 组头/组体/组脚由 `compactionGroupView.ts` 渲染 ✓。
	 * 泛型实参 = 本类型自身 ⇒ 组内归档消息有**完整类型**（无需 as 断言 ✓）。
	 */
	compactionGroup?: ICompactionGroupMeta<IAgentChatMessage>;
	attachments?: IChatAttachment[];
	subAgents?: ISubAgentData[];
	confirmation?: IConfirmationData;
	/** AskUser cards attached to this message (workflow interactive input) */
	askUsers?: ILiveWorkflowAskUser[];
	/**
	 * ImagePicker 交互选择卡（2026-09-11 用户需求）：执行到 picker 阶段时暂停，
	 * 卡片展示上游候选图，用户勾选（多选）后 resume，下游才继续执行。
	 */
	pickerSelects?: ILiveWorkflowPickerSelect[];
	/**
	 * 节点交互表单卡（2026-09-11 用户需求：**通用框架**）：任意节点可在执行前
	 * 声明一张与用户交互的卡片表单（如静态表情包的 m×n / 每格提示词 / 风格），
	 * 用户提交后该节点才执行、随后继续下游。
	 */
	nodeInteractions?: ILiveWorkflowNodeInteraction[];
	/** Todo list for task tracking */
	todos?: ITodoItem[];
	/** Plan tasks generated by the plan workflow (plan_exit) — rendered as a dedicated card */
	planTasks?: IPlanTaskCard;
	/** Suggested questions for user to ask */
	questions?: ISuggestedQuestion[];
	/** References used by AI (files, code, etc.) */
	references?: IReferenceItem[];
	/** Tip message (dismissible) */
	tip?: ITipMessage;
	/** Progress messages for tool execution */
	progress?: IProgressMessage[];
	/** LiveWorkflowTraceView: workflow executions attached to this message */
	workflowExecutions?: Record<string, ILiveWorkflowExecution>;
	/** LiveWorkflowTraceView: workflow events timeline */
	workflowEvents?: ILiveWorkflowEvent[];
	/** LiveWorkflowTraceView: collect variables requests */
	collectVariables?: Record<string, ILiveCollectVariable>;
	/** Structured task card data — when set, the renderer builds the task
	 *  prompt card from this data instead of regex-parsing the text content. */
	taskCard?: { title: string; description: string; source?: string; taskId?: string; dependencies?: readonly string[]; attachments?: readonly { name: string; mimeType: string }[] };
}

/** File/image/folder attachment for chat messages */
export interface IChatAttachment {
	id: string;
	type: 'image' | 'file' | 'folder';
	name: string;
	mimeType: string;
	/** base64（image）| utf8 文本（file）| 系统路径（folder） */
	data: string;
	size: number;
	isPasted?: boolean;
	/** 原始文件路径 / 文件夹路径（点击附件时在编辑器中打开，或交给 agent 操作） */
	filePath?: string;
	/** 2026-09-18：文本片段种类，仅影响 chip 图标/名称/预览标题，不改变发送内容。
	 *  可选——既有构造点（文件/图片/文件夹/addTextContext）不受影响。 */
	kind?: 'snippet' | 'log';
}

/** Sub-agent spawned during a conversation turn */
export interface ISubAgentData {
	id: string;
	/** Agent type badge. Fixed values: 'explore' | 'general' | 'scout' — or any registered agent name (e.g. 'code-explorer', 'researcher', 'data'). */
	type: string;
	task: string;
	parentAgentId?: string;
	status: 'pending' | 'running' | 'done' | 'error' | 'cancelled';
	progress?: string;
	output?: string;
	/** 累积的实时文本（running 时显示），Completed 后由 output 替代 */
	streamingOutput?: string;
	error?: string;
	groupId?: string;
	/** P0: Links the subagent card to its parent plan_explore / delegate_task tool card. */
	parentToolCallId?: string;
	/** Live thinking text emitted by the sub-agent during execution (running only) */
	thinking?: string;
	/** 子代理开始/结束时间（epoch ms），供 UI 计算时长（时间 chip 与页脚统计）。 */
	startedAt?: number;
	completedAt?: number;
	/**
	 * ★ 2026-09-13：**累计** token 用量（input/output），**执行过程中实时更新**。
	 *
	 * 数据链：`unifiedSubAgentDispatch` 的 usage delta（每个 LLM turn 一条）
	 * → `SubAgentEventType.Progress`（带 tokensUsed）→ `reduceCardState`
	 * → `fireSubAgentTrace` → pane → 此处 → 卡片 header 展示。
	 */
	tokensUsed?: { input: number; output: number };
	/**
	 * ★ 2026-09-13：**累计**积分消耗（网关 `usage.credit`），执行过程中实时更新。
	 *
	 * 数据链与 `tokensUsed` 完全平行：`unifiedSubAgentDispatch` 的 usage delta
	 * → `SubAgentEventType.Progress` → `reduceCardState` → `fireSubAgentTrace`
	 * → pane → 此处 → 卡片左下角展示。
	 */
	creditUsed?: number;
	/** Enhanced blocks (matches React SubAgentCard block system) */
	inputBlocks?: ISubAgentBlock[];
	thinkingBlocks?: ISubAgentBlock[];
	toolTraces?: ISubAgentToolTrace[];
	outputBlocks?: ISubAgentBlock[];
}

export interface ISubAgentBlock {
	id: string;
	title?: string;
	content: string;
	collapsed?: boolean;
}

export interface ISubAgentToolTrace {
	id: string;
	name: string;
	status: 'running' | 'done' | 'error';
	args?: string;
	result?: string;
}

/** Ask/Confirmation data for interactive cards */
export interface IConfirmationData {
	id: string;
	title: string;
	message: string;
	detail?: string;
	buttons: Array<{ id: string; label: string; primary?: boolean; danger?: boolean }>;
	status: 'pending' | 'approved' | 'rejected' | 'cancelled';
	/** Security level badge */
	securityLevel?: 'safe' | 'cautious' | 'dangerous';
	/** Auto-confirm options (once/session/workspace/always) */
	autoConfirmOptions?: Array<{ id: string; label: string }>;
	/** Terminal command (for terminal confirmation cards) */
	command?: string;
	/** Tool call name (to identify terminal tools) */
	toolName?: string;
	/** 关联的工具调用 ID（沙箱确认内嵌到对应工具卡片时使用） */
	toolCallId?: string;
}

/**
 * 工具审批卡片数据（2026-08-21）。
 *
 * 挂在 **IToolCall 上**（而不是 message.confirmation）——工具卡片的所有重建路径
 * （parts 渲染 / _ruleToolStatusSync / progress 补建 / 历史恢复）都会带上 tc，
 * 而 `msg.confirmation` 在多条重建路径上根本没被传入 `_createToolCallCard`，
 * 挂在 message 上会导致审批按钮在任意一次重绘后消失。
 *
 * 不参与持久化（adaptPersistedToolCall 白名单不含 approval）：窗口刷新后
 * 宿主进程里的 pending promise 已随 turn 结束，恢复出一个「可点击但点了没人接」
 * 的审批区反而是坑。
 */
export interface IToolApprovalCardData {
	/** = 工具调用 ID（命令 agentStudio.confirmationAction 按此 id 路由决策） */
	id: string;
	toolName: string;
	reason?: string;
	securityLevel?: 'safe' | 'cautious' | 'dangerous';
	/** 审批截止时间戳（epoch ms）——UI 按此渲染倒计时 */
	deadline?: number;
	/** 审批等待上限（毫秒） */
	timeoutMs?: number;
	/** pending 时渲染按钮；其余状态定格为结果文案 */
	status: 'pending' | 'approved' | 'rejected' | 'timeout' | 'cancelled';
}

/**
 * 输入框 ChatMode 下拉框的 UI 元数据（2026-08-21）。
 *
 * 与 `contrib/agentStudio/common/chatModeConfig.ts` 的 `CHAT_MODE_INFO` 内容对齐，
 * 但**刻意在此重新声明**：`src/vs/sessions/browser/agentChat/` 是通用聊天 UI 目录，
 * 不应反向依赖 `contrib/agentStudio/**` 内部模块（会造成分层倒置）。
 *
 * ⚠ 只含输入框可选的 3 档。`workflow` 档不在此列 —— 它由工作流编辑器上下文
 * 自行驱动，不作为用户在聊天输入框里的手选项。
 */
export const CHAT_MODE_UI: Readonly<Record<'craft' | 'ask' | 'plan', {
	readonly label: string;
	readonly description: string;
	readonly svgPath: string;
}>> = {
	craft: {
		label: 'Craft',
		description: '完整工具访问，可直接修改代码和执行命令',
		svgPath: 'M13 2L3 14h9l-1 8 10-12h-9l1-8z', // lightning bolt
	},
	ask: {
		label: 'Ask',
		description: '只读工具访问，提供技术解答和建议',
		svgPath: 'M12 2a10 10 0 100 20 10 10 0 000-20zm0 4a1.5 1.5 0 110 3 1.5 1.5 0 010-3zm1 5.5v5h-2v-5h2z', // info circle
	},
	plan: {
		label: 'Plan',
		description: '只读探索 + 任务拆解，可使用 Plan 工具（其他模式不可用）',
		svgPath: 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4', // clipboard list
	},
};

/** 输入框可选的 ChatMode 顺序（下拉框渲染顺序）。 */
export const CHAT_MODE_ORDER: ReadonlyArray<'craft' | 'ask' | 'plan'> = ['craft', 'ask', 'plan'];

/** Tool call within a message */
export interface IToolCall {
	id: string;
	name: string;
	args?: string;
	result?: string;
	/** Status: running | success | error | approval_required | rejected | pending | canceled | skipped */
	status?: 'running' | 'success' | 'error' | 'approval_required' | 'rejected' | 'pending' | 'canceled' | 'skipped';
	displayName?: string;
	renderType?: string;
	defaultShow?: boolean;
	/**
	 * @deprecated 阶段E 起改用有序 `IAgentChatMessage.parts`。仅迁移期可读。
	 */
	textPosition?: number;
	/** File path associated with this tool call (e.g., for edit_file tools) */
	filePath?: string;
	/** Execution duration in milliseconds */
	duration?: number;
	/** Error message if the tool failed */
	error?: string;
	/** 实时进度 0-100（workflow 直接执行 / ComfyUI 生成等长耗时工具卡）。 */
	progress?: number;
	/** 实时进度的人类可读描述（如「生成中 42%」）。 */
	progressText?: string;
	/** Process exit code (for terminal tools) */
	exitCode?: number;
	/** Security level for approval UI */
	securityLevel?: 'safe' | 'cautious' | 'dangerous';
	/**
	 * 等待用户审批时的卡内审批区数据（含倒计时截止时间）。
	 * 由 nativeChatEditorPane 订阅 IAgentOSService.onDidRequestToolApproval 写入。
	 */
	approval?: IToolApprovalCardData;
	/** Whether this tool was server-executed (no client confirmation needed) */
	serverExecuted?: boolean;
	/**
	 * plan_enter / plan_explore 工具卡附带的规划阶段进度（WorkMode 阶段卡数据）。
	 * 由 work_mode_changed delta 驱动更新，随 toolCalls/parts 持久化——
	 * 窗口刷新后从历史恢复，阶段卡不丢失（adaptPersistedToolCall 白名单透传）。
	 */
	planPhase?: {
		/** 0-based 当前进行中的阶段（P1 理解需求 / P2 并行探索 / P3 方案设计 / P4 撰写计划 / P5 提交执行） */
		currentStep?: number;
		/** 计划文件绝对路径 */
		planFilePath?: string;
		/** 完成时间戳（plan_exit 后定格完成态） */
		completedAt?: number;
	};
	/** Sub-agent data spawned by this tool call (delegate_task / plan_explore).
	 *  Attached directly to the tool call so the card renders sub-agent info inline.
	 *  Replaces the old independent `{ kind: 'subagent' }` parts approach. */
	subAgents?: ISubAgentData[];
}

/** 文本内容片段（阶段E 有序模型） */
export interface ITextMessagePart {
	readonly kind: 'text';
	text: string;
}

/** 工具调用片段（阶段E 有序模型） */
export interface IToolMessagePart {
	readonly kind: 'tool';
	tool: IToolCall;
}

/**
 * 思考片段（2026-07-26）：thinking 跟随 LLM 流式输出的实际发生位置，
 * 作为 parts 流的一部分按序渲染（不固定在气泡顶部/底部）。
 * 每个思考 episode（一轮 LLM 响应内的 thinking 段）一个 part；
 * text 为该 episode 的累积 thinking 文本。
 */
export interface IThinkingMessagePart {
	readonly kind: 'thinking';
	text: string;
}

/**
 * assistant 消息有序片段。渲染按顺序遍历：文本段→markdown，工具段→工具卡，
 * 思考段→thinking 卡（就地位置）。
 */
export type IMessagePart = ITextMessagePart | IToolMessagePart | IThinkingMessagePart;

// 子代理不再以独立 part 渲染（路径 B 已移除）。
// 子代理卡片仅通过路径 A 承载：tool call 的 tool.subAgents（delegate/explore 卡内聚合 chip/progress）
// 与消息级 msg.subAgents（气泡内 .subagent-cards-section 独立详情卡）。
// 旧持久化数据中的 { kind: 'subagent' } part 由 adaptPersistedChatMessage 迁移到 tool.subAgents。

/** 由有序片段派生扁平字段（content=文本拼接，toolCalls=工具列表，子agent卡片不参与扁平化）。 */
export function flattenMessageParts(parts: readonly IMessagePart[]): { content: string; toolCalls: IToolCall[] } {
	let content = '';
	const toolCalls: IToolCall[] = [];
	for (const p of parts) {
		if (p.kind === 'text') {
			content += p.text;
		} else if (p.kind === 'tool') {
			toolCalls.push(p.tool);
		}
		// subagent parts do not contribute to content/toolCalls
	}
	return { content, toolCalls };
}

/**
 * 读取期迁移：由 content + 内嵌 toolCalls（含 textPosition）派生有序 parts。
 * 与持久化层 deriveMessageParts 同算法，但作用于 UI 侧 IToolCall。
 * 规则：positioned 工具按偏移切分文本；unpositioned 工具排在末尾；
 * 无工具时仅一个文本片段（content 非空）。
 */
export function deriveUiMessageParts(content: string, toolCalls: readonly IToolCall[]): IMessagePart[] {
	const text = content ?? '';
	const tcs = toolCalls ?? [];
	if (tcs.length === 0) {
		return text.length > 0 ? [{ kind: 'text', text }] : [];
	}
	const positioned = tcs
		.filter(tc => typeof tc.textPosition === 'number' && (tc.textPosition as number) >= 0)
		.slice()
		.sort((a, b) => (a.textPosition as number) - (b.textPosition as number));
	const unpositioned = tcs.filter(tc => typeof tc.textPosition !== 'number' || (tc.textPosition as number) < 0);

	const parts: IMessagePart[] = [];
	let lastPos = 0;
	for (const tc of positioned) {
		const pos = Math.min(Math.max(tc.textPosition as number, 0), text.length);
		if (pos > lastPos) {
			const seg = text.slice(lastPos, pos);
			if (seg.length > 0) { parts.push({ kind: 'text', text: seg }); }
		}
		parts.push({ kind: 'tool', tool: tc });
		lastPos = Math.max(lastPos, pos);
	}
	if (lastPos < text.length) {
		const seg = text.slice(lastPos);
		if (seg.length > 0) { parts.push({ kind: 'text', text: seg }); }
	} else if (positioned.length === 0 && text.length > 0) {
		parts.push({ kind: 'text', text });
	}
	for (const tc of unpositioned) {
		parts.push({ kind: 'tool', tool: tc });
	}
	return parts;
}

/** 将一个持久化 ToolCall（任意来源字段名）规整为 UI 的 IToolCall。 */
export function adaptPersistedToolCall(c: any, i: number): IToolCall {
	return {
		id: c?.id ?? `tc-${i}`,
		name: c?.name ?? 'tool',
		// 持久化字段名为 `arguments`，兼容历史可能写入的 `args`。
		args: typeof c?.arguments === 'string'
			? c.arguments
			: (typeof c?.args === 'string'
				? c.args
				: (c?.arguments !== undefined
					? JSON.stringify(c.arguments)
					: (c?.args !== undefined ? JSON.stringify(c.args) : undefined))),
		result: typeof c?.result === 'string' ? c.result : (c?.result ? JSON.stringify(c.result) : undefined),
		// 持久化 status 'running'|'done'|'error' → UI 'running'|'success'|'error'（保留 error 失败态）。
		status: c?.status === 'running' ? 'running' : (c?.status === 'error' ? 'error' : 'success'),
		// textPosition 仅供本次派生 parts 使用，不再向后传递。
		textPosition: typeof c?.textPosition === 'number' ? c.textPosition : undefined,
		displayName: typeof c?.displayName === 'string' ? c.displayName : undefined,
		renderType: typeof c?.renderType === 'string' ? c.renderType : undefined,
		defaultShow: typeof c?.defaultShow === 'boolean' ? c.defaultShow : undefined,
		error: typeof c?.error === 'string' ? c.error : undefined,
		filePath: typeof c?.filePath === 'string' ? c.filePath : undefined,
		duration: typeof c?.duration === 'number' ? c.duration : undefined,
		exitCode: typeof c?.exitCode === 'number' ? c.exitCode : undefined,
		// plan_enter/plan_explore 阶段卡进度（白名单透传——缺失会使刷新后阶段卡丢失）
		planPhase: (c?.planPhase && typeof c.planPhase === 'object') ? {
			currentStep: typeof c.planPhase.currentStep === 'number' ? c.planPhase.currentStep : undefined,
			planFilePath: typeof c.planPhase.planFilePath === 'string' ? c.planPhase.planFilePath : undefined,
			completedAt: typeof c.planPhase.completedAt === 'number' ? c.planPhase.completedAt : undefined,
		} : undefined,
	};
}

/**
 * 统一的持久化消息 → 面板消息适配（阶段E：两个宿主共用入口）。
 * - 过滤独立 'tool' 角色消息（返回 null）；工具卡片由 assistant 的有序 parts 承载。
 * - assistant 消息总是带 parts（优先用已存的 parts，否则由 content+toolCalls 派生）。
 * 调用方：`history.map(adaptPersistedChatMessage).filter((m): m is IAgentChatMessage => !!m)`。
 */
export function adaptPersistedChatMessage(
	m: any,
	/** ★ 2026-09-22：opt-in 保留压缩边界（默认 false ⇒ 行为逐字不变 ✓）。 */
	opts?: { readonly keepCompactionBoundary?: boolean },
): IAgentChatMessage | null {
	if (!m) { return null; }
	if (m.role === 'tool') { return null; }
	// 过滤 compaction 边界消息——它是 LLM 上下文管理的内部标记
	// （由 sliceAtCompactionBoundary 用于历史切片），不应作为普通
	// assistant 气泡渲染在聊天 UI 中。
	//
	// ★ 2026-09-22（用户选定方案 C「收纳手风琴」）：**opt-in 保留** ✓ ——
	//   `nativeChatEditorPane._adaptHistoryMessages` 传 `keepCompactionBoundary:true`，
	//   把它适配为一条**系统消息**（metadata.type 原样保留 ✓），随后交给
	//   `coalesceCompactionGroups` 决定"收纳成组 / 只留提示行" ✓✓。
	//   ⚠ 默认（不传 opts）行为**逐字不变**：仍返回 null ⇒ 其它宿主与既有测试零影响 ✓。
	if (m.metadata?.type === 'compaction') {
		if (!opts?.keepCompactionBoundary) { return null; }
		const boundaryTs = (() => {
			const t = typeof m.timestamp === 'string' ? Date.parse(m.timestamp) : Number(m.timestamp);
			return Number.isFinite(t) ? t : Date.now();
		})();
		return {
			id: typeof m.id === 'string' && m.id.length > 0 ? m.id : `compaction-boundary-${boundaryTs}`,
			role: 'system',
			content: m.content ?? '',
			timestamp: boundaryTs,
			metadata: m.metadata,
		};
	}
	const role: IAgentChatMessage['role'] = m.role === 'user' ? 'user' : (m.role === 'assistant' ? 'assistant' : 'system');
	const ts = (() => {
		const t = typeof m.timestamp === 'string' ? Date.parse(m.timestamp) : Number(m.timestamp);
		return Number.isFinite(t) ? t : Date.now();
	})();
	const toolCalls: IToolCall[] | undefined = Array.isArray(m.toolCalls)
		? m.toolCalls.map((c: any, i: number) => adaptPersistedToolCall(c, i))
		: undefined;

	let parts: IMessagePart[] | undefined;
	if (role === 'assistant') {
		if (Array.isArray(m.parts) && m.parts.length > 0) {
			// 新格式：parts 已落盘，工具片段内的 tool 字段同样规整为 IToolCall。
			parts = m.parts.map((p: any): IMessagePart => {
				if (p?.kind === 'tool') {
					return { kind: 'tool', tool: adaptPersistedToolCall(p.tool, 0) };
				}
				if (p?.kind === 'subagent' && p.subAgent) {
					// 旧格式迁移：subagent 片段 → 归入父 tool call 的 subAgents
					// (在下方迁移逻辑中处理)
					return null as any;
				}
				if (p?.kind === 'thinking') {
					// 2026-07-26：thinking 片段按原样恢复（跟随流式位置模型）
					return { kind: 'thinking', text: typeof p?.text === 'string' ? p.text : '' };
				}
				return { kind: 'text', text: typeof p?.text === 'string' ? p.text : '' };
			}).filter((p: any) => p !== null);
			// 迁移旧 subagent 片段到父 tool call 的 subAgents
			const oldSubagentParts = (m.parts as any[]).filter((p: any) => p?.kind === 'subagent' && p.subAgent);
			if (oldSubagentParts.length > 0 && toolCalls) {
				for (const sp of oldSubagentParts) {
					const ptc = sp.subAgent.parentToolCallId;
					if (ptc) {
						const parentTc = toolCalls.find(tc => tc.id === ptc);
						if (parentTc) {
							if (!parentTc.subAgents) { parentTc.subAgents = []; }
							parentTc.subAgents.push(sp.subAgent);
						}
					}
				}
			}
		} else {
			// 旧格式：由 content + toolCalls(textPosition) 派生。
			parts = deriveUiMessageParts(m.content ?? '', toolCalls ?? []);
		}
		// 2026-07-26：旧消息的 thinking 字符串 → thinking part（跟随流式位置模型）。
		// 恢复场景无逐 episode 位置信息，放在 parts 起始处（思考先于输出的标准位置）。
		if (typeof m.thinking === 'string' && m.thinking.length > 0
			&& parts && !parts.some(p => p.kind === 'thinking')) {
			parts.unshift({ kind: 'thinking', text: m.thinking });
		}
		// 恢复 msg.subAgents 到对应 tool call 的 subAgents（旧数据兼容）
		if (Array.isArray(m.subAgents) && m.subAgents.length > 0 && toolCalls) {
			for (const sa of m.subAgents) {
				if (!sa?.parentToolCallId) continue;
				const parentTc = toolCalls.find(tc => tc.id === sa.parentToolCallId);
				if (parentTc && !parentTc.subAgents) {
					parentTc.subAgents = m.subAgents.filter((s: ISubAgentData) => s?.parentToolCallId === sa.parentToolCallId);
				}
			}
		}
	}

	// ── 恢复工作流相关字段（这些字段在持久化时由 agentChatPanel 写入）───
	// workflowExecutions: Record<string, ILiveWorkflowExecution>
	let workflowExecutions: Record<string, ILiveWorkflowExecution> | undefined;
	if (m.workflowExecutions && typeof m.workflowExecutions === 'object') {
		workflowExecutions = m.workflowExecutions;
	}
	// workflowEvents: ILiveWorkflowEvent[]
	let workflowEvents: ILiveWorkflowEvent[] | undefined;
	if (Array.isArray(m.workflowEvents)) {
		workflowEvents = m.workflowEvents;
	}
	// collectVariables: Record<string, ILiveCollectVariable>
	let collectVariables: Record<string, ILiveCollectVariable> | undefined;
	if (m.collectVariables && typeof m.collectVariables === 'object') {
		collectVariables = m.collectVariables;
	}
	// askUsers: ILiveWorkflowAskUser[]
	let askUsers: ILiveWorkflowAskUser[] | undefined;
	if (Array.isArray(m.askUsers)) {
		askUsers = m.askUsers;
	}

	return {
		id: m.id,
		role,
		content: m.content ?? '',
		timestamp: ts,
		turnId: m.turnId,
		thinking: m.thinking,
		toolCalls,
		parts,
		isStreaming: m.isStreaming,
		streamPhase: m.streamPhase,
		metadata: m.metadata,
		tokenUsage: m.tokenUsage,
		workflowExecutions,
		workflowEvents,
		collectVariables,
		askUsers,
		// Preserve taskCard structured data so the chat renderer can build
		// the task prompt card from it after a history reload (P2-11 fix).
		// Without this, the field is dropped during adaptation and the card
		// only shows for live messages, not reloaded ones.
		taskCard: m.taskCard,
		// ★★ 2026-09-19：附件随历史**回灌**（否则重启后气泡丢代码片段 pill ✗✓ ——
		// 持久化侧见 `ChatMessage.attachments` ✓）。持久化时已过滤图片 ⇒ 这里都是
		// 可恢复的文本类附件 ✓；`kind` 随对象回来 ⇒ 恢复后仍是「代码片段」pill ✓。
		attachments: Array.isArray(m.attachments) ? m.attachments : undefined,
	};
}

/**
 * ★ 2026-09-22（用户选定方案 C「收纳手风琴」）：把"已滚出模型视野"的历史区间**收纳**为
 * 一个分组消息（组头/组体/组脚由 `compactionGroupView.ts` 渲染 ✓）。
 *
 * **为什么放在适配层而不是渲染层**（关键设计决策 ✓）：
 *   收纳是**消息语义**变换，不是渲染细节 ✗✓。变换后 `_messages` 与 DOM 仍是 **1:1** ✓ ⇒
 *   懒加载分块（按 index 取 `_messages[i]` 建元素 ✓）、DOM 裁剪（`firstElementChild` +
 *   `data-msg-id` 反查下标 ✓）、导航计数、滚动锚点、滚动条标记**全部照旧** ✓✓。
 *   反之若在渲染层"包一层容器"，`firstElementChild` 就不再是消息元素 ⇒ 会打断这些既有映射 ✗✓。
 *
 * **不做收纳的两种情形**（都由 `planCompactionGroup` 判定 ✓ 判据唯一真源于 historyCompaction ✓）：
 *   · 边界**不可信**（摘要饥饿 / tokensSaved<=0 / 空摘要）⇒ 模型其实仍看得见全部历史 ⇒
 *     收纳就是在**撒谎** ✗✓；边界消息原样留在数组里 ⇒ 视图渲染为**提示行** ✓。
 *   · 边界之前已无可收纳内容（边界位于首位）⇒ 不建空组 ✓。
 */
export function coalesceCompactionGroups(
	messages: readonly IAgentChatMessage[],
	/** ★ 2026-09-22：透传收纳计划选项（默认 = **移除模式** ⇒ 不持有原文 ✓✓）。 */
	opts?: ICompactionGroupOptions,
): IAgentChatMessage[] {
	const plan = planCompactionGroup(messages, opts);
	if (!plan.hasGroup || !plan.group) { return messages.slice(); }
	const group = plan.group;
	const tail = messages.slice(plan.archiveEnd);
	const boundary = messages[plan.archiveEnd - 1];
	const synthetic: IAgentChatMessage = {
		// id 稳定（`compaction-group:<边界id>` ✓）⇒ 折叠状态可跨 rebuild / 懒加载重渲染保留 ✓
		id: group.id,
		role: 'system',
		// content = 摘要正文 ⇒ 导航/搜索仍能命中摘要文本 ✓（归档原文不再逐条列出，见报告 ✓）
		content: group.summary,
		timestamp: boundary?.timestamp ?? Date.now(),
		compactionGroup: group,
	};
	return [synthetic, ...tail];
}

/** Status display mapping */
export const STATUS_MAP: Record<AgentStatus, { label: string; color: string; bg: string; dot: string; animated: boolean }> = {
	[AgentStatus.Idle]:     { label: '空闲',   color: '#9ca3af',  bg: 'rgba(255,255,255,0.05)', dot: '#9ca3af',  animated: false },
	[AgentStatus.Working]:  { label: '工作中', color: '#4ade80',  bg: 'rgba(74,222,128,0.08)',  dot: '#4ade80',  animated: true  },
	[AgentStatus.Thinking]: { label: '思考中', color: '#7cb9ff',  bg: 'rgba(124,185,255,0.08)', dot: '#7cb9ff',  animated: true  },
	[AgentStatus.Error]:     { label: '出错',   color: '#e94560',  bg: 'rgba(233,69,96,0.08)',   dot: '#e94560',  animated: false },
	[AgentStatus.Offline]:   { label: '离线',   color: '#6b7280',  bg: 'rgba(255,255,255,0.02)', dot: 'rgba(255,255,255,0.2)', animated: false },
};

/** Agent info passed to the chat panel */
export interface IAgentInfo {
	readonly id: string;
	readonly name: string;
	readonly role: string;
	readonly avatarUrl?: string;
	/** Icon emoji for the agent (e.g. '🦞', '👨‍💻') — used as fallback when avatarUrl is not available */
	readonly icon?: string;
	readonly status: AgentStatus;
	readonly isPM?: boolean;
	readonly customPrompt?: string;
	readonly model?: string;
	readonly provider?: string;
}

/** Provider info for model selector */
export interface IProviderInfo {
	readonly id: string;
	readonly label: string;
	/** Whether the provider supports agent selection (e.g. knot) */
	readonly supportsAgents?: boolean;
	/** Available agents for this provider (only if supportsAgents is true) */
	readonly agents?: IProviderAgentInfo[];
}

/** Agent info for provider's agent list */
export interface IProviderAgentInfo {
	readonly id: string;
	readonly name: string;
	readonly models?: string[];
}

/** Model info for model selector */
export interface IModelInfo {
	readonly id: string;
	readonly label: string;
	readonly provider: string;
	/** Whether the model supports image input (vision capability) */
	readonly supportsImages?: boolean;
	/** Maximum input tokens (context window limit) */
	readonly maxInputTokens?: number;
}

/**
 * 「图片模型」下拉的一级分组：按 provider 归类其图片生成模型。
 *
 * 2026-09-10 新增。数据由 pane 侧从 `IModelSelectorService.getAvailableModels()`
 * 的结果中筛出 `model.supportsImageGen === true` 后按 provider 分组得到，
 * 不新增任何后端调用。
 *
 * 偏好字符串（写入 `_currentImageModel`，经 `onSelectImageModel` 回传 pane）：
 *   - `''`                                → 未配置（chip 显示占位「图片模型」，下游按默认路由）
 *   - `'provider:<providerId>:<modelId>'` → 指定 provider 下的具体图片模型
 * 注：不提供「自动」选项（2026-09-10 按产品决策移除），未配置即等价自动路由。
 * 注：本仓库另有 ComfyUI 图片后端（`ImageGenBackendRegistry`），但按产品决策
 * **不在本下拉中暴露**（仅 provider 后端）。
 */
export interface IImageModelGroup {
	readonly providerId: string;
	readonly providerLabel: string;
	readonly models: ReadonlyArray<{ readonly id: string; readonly label: string }>;
}

/** Stream phase — precise state machine for streaming lifecycle (Void-inspired 5-state model).
 *
 *  State transitions:
 *    idle → llm_streaming → tool_executing → llm_streaming → ... → idle
 *    idle → llm_streaming → awaiting_approval → tool_executing → ... → idle
 *    idle → llm_streaming → compressing → llm_streaming → ... → idle
 *    * → error → idle
 */
export type StreamPhase = 'idle' | 'llm_streaming' | 'tool_executing' | 'awaiting_approval' | 'retrieving' | 'compressing' | 'error' | 'canceled';

/** Chat mode — mirrors webview ChatMode */
export type ChatMode = 'craft' | 'ask' | 'plan' | 'workflow';

/** Mode option metadata for the composer mode dropdown */
export interface IModeOption {
	readonly id: ChatMode;
	readonly label: string;
	readonly description: string;
	readonly icon: string;       // SVG path d=
}

/** Header dropdown panel types (toolbar buttons) */
export type HeaderPanelType =
	| 'worktree'
	| 'message-nav'
	| 'history'
	| 'settings'
	| null;

/** Worktree info for header dropdown */
export interface IWorktreeItem {
	readonly path: string;
	readonly branch: string;
	/** Number of outgoing changes (local commits not pushed) */
	readonly outgoingChanges?: number;
	/** Number of incoming changes (commits from remote) */
	readonly incomingChanges?: number;
	/** Number of uncommitted changes (working tree modifications) */
	readonly uncommittedChanges?: number;
}

/** Lightweight summary of a user message — fed into the message-nav dropdown */
export interface IMessageNavItem {
	readonly id: string;
	readonly summary: string;
	readonly timestamp: number;
}

/** Workspace selector item — displayed in the input-area toolbar workspace dropdown */
export interface IWorkspaceItem {
	readonly id: string;
	readonly name: string;
	readonly path: string;
}

/** Session info bar payload */
export interface ISessionInfo {
	readonly mode: ChatMode;
	readonly superior?: { id: string; name: string };
	readonly subordinates?: ReadonlyArray<{ id: string; name: string }>;
	readonly taskCount: number;
}

/** Agent session metadata for the chat-history side panel */
export interface IAgentSessionMeta {
	readonly id: string;
	readonly name: string;
	readonly createdAt: string;
	readonly updatedAt: string;
	readonly messageCount: number;
}

/** Token usage snapshot used to render the context-usage ring */
export interface IContextUsage {
	readonly used: number;
	readonly limit: number;
	readonly percent: number; // 0-100
	readonly ratio: number;   // 0-1
	/**
	 * 压缩判定用的有效窗口（2026-09-04）：clamp(模型窗口, 64k, 200k)，
	 * 与 ContextManager._evaluateTrigger 同源（host 经 resolveEffectiveWindow 计算）。
	 * 缺省时 UI 回退用 limit（模型声明 maxInputTokens）——大窗口模型（>200k 被
	 * 硬顶）会出现「环显示 6% 实际已过 30% 压缩线」的口径错位。
	 */
	readonly effectiveWindow?: number;
	/** 压缩触发线 = effectiveWindow × 阈值比例。存在时 UI 环以它为满刻度。 */
	readonly thresholdTokens?: number;
}

/** Checkpoint info for the CheckpointBar */
export interface ICheckpointInfo {
	readonly id: string;
	readonly label: string;
	readonly timestamp: number;
	readonly fileCount: number;
	readonly files: ReadonlyArray<{
		path: string;
		status: 'modified' | 'created' | 'deleted';
		/** 真实行级变更统计（跨检查点累加），供回退确认弹窗展示 +N -M */
		readonly additions?: number;
		readonly deletions?: number;
	}>;
}

/**
 * 队列项 —— 等待执行的待办任务。
 * 渲染在系统栏下方、输入区上方的"队列栏"中。
 */
export interface IQueueItem {
	readonly id: string;
	/** 任务描述（展示在队列行） */
	readonly content: string;
	/** 入队时间戳（毫秒） */
	readonly timestamp: number;
	/** 任务状态 */
	readonly status?: 'pending' | 'executing' | 'done' | 'failed';
	/** 可选元数据（attach/file/agentId 等） */
	readonly metadata?: Record<string, unknown>;
	/**
	 * ★ 2026-09-18（用户需求）：**队列项随附的 pill** —— 代码片段 / 图片 / 文件 / 技能 / 工作流 ✓。
	 *
	 * 为什么需要：入队时原来只留 `content`（纯文本）✗，附件甚至被压成一句
	 * `[2 个附件]` ✗ ⇒ 用户排完队**看不出这条里带了什么** ✓（需要显示 pill）。
	 */
	readonly pills?: ReadonlyArray<IQueuePill>;
}

/**
 * 队列项上的 pill（**展示用**最小结构）。
 *
 * ⚠ 刻意不复用 `IChatAttachment` ✗：pill 里还有 skill / workflow 这类**不是附件**的内联 chip ✓
 * ⇒ 需要一个能同时表达二者的结构 ✓。
 * ⚠ 它只承载"显示什么"，**不承载"发什么"** —— 发送仍走原有的 text/attachments 通路 ✓
 * （因此本字段缺失/不完整不会影响发送行为 ✓）。
 */
export interface IQueuePill {
	/** 形态：决定图标与配色 ✓ */
	readonly kind: 'file' | 'image' | 'folder' | 'snippet' | 'log' | 'skill' | 'workflow';
	/** 主文案（文件名 / 片段名 / 技能名 …）✓ */
	readonly label: string;
	/** 次要信息（大小 / 行数 …）✓ */
	readonly meta?: string;
}

/** 队列项操作类型 */
export type QueueItemActionType = 'promote' | 'edit' | 'delete' | 'reorder';
/** 队列项操作回调（promote/edit/delete/reorder, itemId, newIndex?） */
export type IQueueItemActionCallback = (
	action: QueueItemActionType,
	itemId: string,
	extra?: { newIndex?: number; newContent?: string }
) => void;

// ── AskUser Card ─────────────────────────────────────────
// Interactive card for workflow user input

/** Lightweight option for AskUser card */
export interface IAskUserOption {
	readonly label: string;
	readonly description?: string;
}

/** AskUser entry — interactive card in workflow owner agent's chat */
/**
 * ImagePicker 交互选择卡（2026-09-11 用户需求）。
 *
 * 执行到 ImagePicker 阶段时工作流暂停：卡片渲染上游候选媒体缩略图 + 多选勾选，
 * 用户确认后把选中 refs 作为该节点的输出（snapshot）交给下游，随后 resume 执行。
 * 与 ILiveWorkflowAskUser 同构（同走 pause/resume），但载荷是媒体引用而非选项文本。
 */
export interface ILiveWorkflowPickerSelect {
	readonly id: string;              // `${executionId}:${nodeId}`
	readonly executionId: string;
	readonly nodeId: string;
	readonly nodeName: string;
	/** 上游候选媒体（卡片渲染缩略图；ref 经 _mediaSrc 转 URL）。 */
	readonly candidates: ReadonlyArray<{ port: string; kind: 'image' | 'video' | 'audio' | 'text' | 'unknown'; ref: string; meta?: Record<string, unknown> }>;
	readonly multiSelect: boolean;
	/** 已勾选的 ref（DOM 重渲染间保持）。 */
	selectedRefs: string[];
	readonly status: 'pending' | 'answered' | 'cancelled';
	readonly selection?: ReadonlyArray<string>;
	/** 创建时间（与 AskUser 卡同一交错排序依据）。 */
	readonly createdAt?: number;
}

/**
 * 节点交互表单卡（2026-09-11 用户需求：通用框架）。
 *
 * 任意工作流节点可在**执行前**声明一张与用户交互的卡片表单（字段由 schema 驱动：
 * 数字 / 下拉 / 文本 / 开关 / m×n 网格 / 列表 / 参考图像），用户提交后该节点才执行，
 * 随后继续下游 —— 实现「用户配置完成才进入下一阶段」。与 AskUser / ImagePicker
 * 同走 pause/resume 通道。
 */
export interface ILiveWorkflowNodeInteraction {
	readonly id: string;              // `${executionId}:${nodeId}`
	readonly executionId: string;
	readonly nodeId: string;
	readonly nodeName: string;
	/** 原始节点全名（如 ComfyTV.StatEmojiStage），卡片可据此做专属渲染。 */
	readonly stageClass?: string;
	readonly title: string;
	readonly description?: string;
	readonly submitLabel?: string;
	/** 字段声明（结构与 agentStudio/browser/workflow/nodeInteraction/types.ts 同构）。 */
	readonly fields: ReadonlyArray<Record<string, unknown>>;
	/**
	 * 字段初始值（来自节点现有配置）。特殊键：
	 *  · `__candidates` / `__multiSelect`：选择型节点（apply:'snapshot'）的上游候选媒体，
	 *    存在时卡片**整卡**切到候选缩略图网格模式；
	 *  · `__assetCandidates`：参考图像字段（kind:'image-ref'）的候选（上游图像），
	 *    仅用于字段内的「选择图像」，**不会**切换整卡模式。
	 */
	readonly initialValues: Record<string, unknown>;
	status: 'pending' | 'submitted' | 'skipped';
	submittedValues?: Record<string, unknown>;
	readonly createdAt?: number;
}

export interface ILiveWorkflowAskUser {
	readonly id: string;              // `${executionId}:${nodeId}`
	readonly executionId: string;
	readonly nodeId: string;
	readonly nodeName: string;
	readonly question: string;
	readonly options: ReadonlyArray<IAskUserOption>;
	readonly multiSelect: boolean;
	selectedIndices: number[];
	readonly status: 'pending' | 'answered' | 'cancelled' | 'expired';
	readonly selection?: string | ReadonlyArray<string>;
	/** D3（2026-09-10）：允许自由输入——选项尾部渲染自定义输入框。 */
	readonly allowCustom?: boolean;
	readonly customLabel?: string;
	/** D4：动态参数字段定义（多字段输入表单）。 */
	readonly fields?: ReadonlyArray<{ key: string; label?: string; kind?: string; default?: string; placeholder?: string }>;
	/**
	 * ★ 多问题（2026-09-11）：非空 → 卡片按**单页**渲染全部问题（每问题独立
	 * 模式：选项按钮 / 参数表单），一次提交返回 `answers: { [key]: value }`。
	 * 为空 → 沿用 question/options/fields 的单问题形态（向后兼容）。
	 */
	readonly questions?: ReadonlyArray<{
		readonly key: string;
		readonly text: string;
		readonly mode: 'options' | 'params';
		readonly required?: boolean;
		readonly options?: ReadonlyArray<{ label: string; description?: string }>;
		readonly params?: ReadonlyArray<{ key: string; label?: string; type?: string }>;
		readonly multiSelect?: boolean;
		readonly allowCustom?: boolean;
		readonly customLabel?: string;
	}>;
	readonly createdAt: number;
	readonly answeredAt?: number;
}

// ── TodoList Card ────────────────────────────────────────

/** Todo item for TodoListCard */
export interface ITodoItem {
	readonly id: string;
	readonly label: string;
	readonly completed: boolean;
	readonly description?: string;
	readonly assignee?: string;
}

// ── Plan Tasks Card (plan workflow) ──────────────────────

/** A single task in the plan tasks card */
export interface IPlanTaskItem {
	readonly title: string;
	readonly description?: string;
	readonly files?: string[];
	readonly dependencies?: string[];
	readonly deliverable?: string;
	readonly complexity?: string;
	readonly status?: string;
}

/** Structured plan tasks generated by plan_exit — rendered as a dedicated chat card */
export interface IPlanTaskCard {
	readonly planId?: string;
	readonly summary?: string;
	readonly tasks: IPlanTaskItem[];
}

// ── QuestionCarousel Card ────────────────────────────────
export interface ISuggestedQuestion {
	readonly id: string;
	readonly label: string;
	readonly tooltip?: string;
	readonly category?: string;
}

// ── References Card ──────────────────────────────────────

/** Reference item for ReferencesCard */
export interface IReferenceItem {
	readonly id: string;
	readonly kind: 'file' | 'code' | 'url' | 'symbol' | 'text';
	readonly name: string;
	readonly uri?: string;
	readonly range?: { startLine: number; startCol: number; endLine: number; endCol: number };
	readonly description?: string;
	readonly state?: 'not-modified' | 'modified' | 'pending' | 'excluded';
}

// ── Tip Card ─────────────────────────────────────────────

/** Tip message for TipCard */
export interface ITipMessage {
	readonly id: string;
	readonly content: string;
	readonly icon?: string;
	readonly action?: {
		readonly label: string;
		readonly tooltip?: string;
		readonly actionId: string;  // callback identifier
	};
}

// ── Progress Card ────────────────────────────────────────

/** Progress message for ProgressCard */
export interface IProgressMessage {
	readonly id: string;
	readonly content: string;
	readonly status: 'pending' | 'in-progress' | 'completed' | 'error';
	readonly icon?: 'spinner' | 'check' | 'warning' | 'error';
	readonly timestamp?: string;
}

// ── LiveWorkflowTraceView Types ───────────────────────────

/** Sub-agent node in workflow execution trace */
export interface ILiveWorkflowSubAgent {
	readonly id: string;
	readonly name: string;
	readonly task?: string;
	/**
	 * ★ 卡片图标（P0 修复，2026-09-13）：由 host 的节点描述符给出
	 * （stage kind → 产物语义；否则引擎类型）。此前渲染层用 4 项硬编码表按 `type`
	 * 索引 → 除 agent/prompt/skill/tool 外一律 🤖（含全部 ComfyTV/Saros stage）。
	 * 缺省（历史消息）时渲染层回退旧表。
	 */
	icon?: string;
	readonly status: 'pending' | 'running' | 'done' | 'error' | 'cancelled';
	readonly output?: string;
	readonly error?: string;
	readonly startTime: number;
	endTime?: number;
	/**
	 * 生成进度 0-100（2026-09-11 用户需求：画布生成进度实时同步到对应阶段卡）。
	 * 由 `node_progress` trace 驱动（逐格/逐帧）；仅 running 期间有意义。
	 */
	progress?: number;
	/** 进度附带文案（如「生成中 36%」「第 3/9 格」），作为进度条 tooltip。 */
	progressMessage?: string;
	/** Live streamed text (while running) */
	streamedText?: string;
	/** Live streamed thinking */
	streamedThinking?: string;
	/** Tool calls during execution */
	toolCalls?: Array<{ name: string; status: string; args?: string; result?: string }>;
	/**
	 * 媒体快照（2026-09-10 用户要求：静态表情包节点的生成结果要在工作流卡展示）。
	 * 与 agentStudio 侧 trace 的 snapshot 同构（结构类型，避免跨层 import）；
	 * ref 可能是 data URL / http(s) URL / 本地文件路径——渲染前统一经 _mediaSrc 转换。
	 */
	snapshot?: Array<{ port: string; kind: 'image' | 'video' | 'audio' | 'text' | 'unknown'; ref: string; meta?: Record<string, unknown> }>;
}

/** Workflow execution trace */
export interface ILiveWorkflowExecution {
	readonly executionId: string;
	readonly workflowName: string;
	readonly status: 'running' | 'completed' | 'failed' | 'cancelled';
	readonly currentNodeId?: string;
	readonly subAgents: ILiveWorkflowSubAgent[];
	readonly startTime: number;
	endTime?: number;
	/**
	 * ★ 执行统计（P2-2 修复，2026-09-13）：由 host 在 `execution_end` 里给出
	 * （真实耗时 + 成功/失败/取消/跳过节点数）。
	 *
	 * 此前卡片「耗时」是 controller 用 `Date.now()` 现取 → **恒 0.0s** ✗；
	 * 节点计数则完全没有。渲染见 `agentChatPanel.workflowCards.ts` 的卡片 header。
	 */
	stats?: {
		durationMs?: number;
		doneCount?: number;
		errorCount?: number;
		cancelledCount?: number;
		skippedCount?: number;
	};
}

/** Collect variable for workflow (pre-execution input) */
export interface ILiveCollectVariable {
	readonly id: string;
	readonly executionId: string;
	readonly variables: Array<{ name: string; defaultValue?: string }>;
	readonly values: Record<string, string>;
	readonly status: 'pending' | 'submitted' | 'skipped';
	readonly createdAt: number;
}

/** Workflow event for timeline */
export interface ILiveWorkflowEvent {
	readonly id: string;
	readonly executionId: string;
	readonly sessionId: string;
	readonly timestamp: number;
	readonly kind: 'subagent_start' | 'delta' | 'subagent_end' | 'ask_user' | 'ask_user_end' | 'collect_variables' | 'collect_variables_end' | 'execution_end' | 'breakpoint_hit';
	readonly nodeId: string;
	readonly nodeName?: string;
	readonly nodeType?: string;
	readonly summary?: string;
	readonly ask?: string;
	readonly status?: string;
}

// ── TerminalConfirmationCard Types ───────────────────────────

/** Terminal command confirmation data */
export interface ITerminalConfirmation {
	readonly toolCallId: string;
	readonly command: string;
	readonly riskLevel: 'safe' | 'caution' | 'dangerous';
	readonly status: 'pending' | 'approved' | 'rejected';
}

/** Global unique message ID generator */
let _msgSeq = 0;
export function uniqueMsgId(): string {
	return `msg-${Date.now()}-${(++_msgSeq).toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
}

// ── Orchestration Plan Types (re-exported from agentStudioTypes) ───────────────────────────

export type { OrchestrationPlanStatus, PlanTaskStatus, TaskReviewStatus } from '../../common/agentStudioTypes.js';
export type { OrchestrationPlan, PlanTask, TaskComment } from '../../common/agentStudioTypes.js';

// ── Orchestration Plan Callback Types ─────────────────────────────────────

export interface IOrchestrationCallbacks {
	onApprovePlan: (planId: string) => void;
	onRejectPlan: (planId: string) => void;
	onApproveWithoutExecute: (planId: string) => void;
	onTaskAction: (planId: string, taskId: string, action: 'retry' | 'pause' | 'resume' | 'cancel' | 'approve' | 'reject' | 'block' | 'unblock') => void;
	onUpdatePlan: (planId: string, updates: Record<string, unknown>) => void;
	onUpdateTask: (planId: string, taskId: string, updates: Record<string, unknown>) => void;
	onDecomposeTask: (planId: string, taskId: string) => void;
	onClosePlanDialog: (planId: string) => void;
}

export { AgentStatus };
