/*---------------------------------------------------------------------------------------------
 *  MEMORY.md 桥接 — 双向同步记忆与 MEMORY.md 文件。
 *  参考 agentmemory src/functions/claude-bridge.ts
 *
 *  功能：
 *    - 导出：将长期记忆写入 MEMORY.md（供外部工具读取）
 *    - 导入：读取 MEMORY.md 中的手动编辑，同步回记忆系统
 *    - 增量更新：仅同步变化的条目
 *--------------------------------------------------------------------------------------------*/

interface InternalEntry {
	id: string;
	content: string;
	type: string;
	metadata?: Record<string, unknown>;
	timestamp?: number;
	importance?: number;
	strength: number;
	supersededBy?: string;
}

export interface BridgeConfig {
	enabled: boolean;
	maxEntries: number;
	maxLineBudget: number; // max lines in MEMORY.md
}

export const DEFAULT_BRIDGE_CONFIG: BridgeConfig = {
	enabled: true,
	maxEntries: 50,
	maxLineBudget: 200,
};

export class ClaudeBridge {
	private _lastSyncHash = new Map<string, string>();

	/**
	 * Export memories to MEMORY.md format.
	 * Returns the markdown content.
	 */
	export(agentId: string, entries: InternalEntry[], config: BridgeConfig = DEFAULT_BRIDGE_CONFIG): string {
		const active = entries
			.filter(e => !e.supersededBy && e.strength > 0.15)
			.sort((a, b) => (b.importance ?? 5) - (a.importance ?? 5))
			.slice(0, config.maxEntries);

		const lines: string[] = [];
		lines.push('# Memory');
		lines.push('');
		lines.push('> Auto-generated by AgentMemory. Do not edit manually (changes will be overwritten on next sync).');
		lines.push(`> Last updated: ${new Date().toISOString()}`);
		lines.push(`> Entries: ${active.length}/${entries.length} (filtered by strength > 0.15)`);
		lines.push('');

		// Group by type
		const byType = new Map<string, InternalEntry[]>();
		for (const entry of active) {
			const type = entry.type || 'general';
			const arr = byType.get(type) ?? [];
			arr.push(entry);
			byType.set(type, arr);
		}

		const typeLabels: Record<string, string> = {
			'long_term': 'Long-term Memory',
			'short_term': 'Recent Context',
			'pattern': 'Patterns',
			'preference': 'Preferences',
			'architecture': 'Architecture',
			'bug': 'Known Bugs',
			'workflow': 'Workflows',
			'fact': 'Facts',
		};

		let lineCount = lines.length;
		for (const [type, items] of byType) {
			if (lineCount >= config.maxLineBudget) break;
			lines.push(`## ${typeLabels[type] ?? type}`);
			for (const item of items) {
				if (lineCount >= config.maxLineBudget) break;
				const importance = item.importance ? ` [${item.importance}/10]` : '';
				const strength = ` (strength: ${item.strength.toFixed(2)})`;
				const content = item.content.replace(/\s+/g, ' ').slice(0, 200);
				lines.push(`-${importance} ${content}${strength}`);
				lineCount++;
			}
			lines.push('');
		}

		return lines.join('\n');
	}

	/**
	 * Parse MEMORY.md and extract manually added entries.
	 * Only parses entries NOT marked as auto-generated.
	 */
	import(markdown: string): Array<{ content: string; type: string; importance: number }> {
		const entries: Array<{ content: string; type: string; importance: number }> = [];
		const lines = markdown.split('\n');

		let currentType = 'fact';
		for (const line of lines) {
			const trimmed = line.trim();
			if (trimmed.startsWith('## ')) {
				const heading = trimmed.slice(3).toLowerCase();
				if (heading.includes('preference')) currentType = 'preference';
				else if (heading.includes('pattern')) currentType = 'pattern';
				else if (heading.includes('architecture')) currentType = 'architecture';
				else if (heading.includes('bug')) currentType = 'bug';
				else if (heading.includes('workflow')) currentType = 'workflow';
				else currentType = 'fact';
				continue;
			}

			// Parse list items: "- [8/10] content (strength: 0.85)"
			if (trimmed.startsWith('- ')) {
				const body = trimmed.slice(2);
				// Extract importance
				let importance = 5;
				const impMatch = body.match(/^\[(\d+)\/10\]\s*/);
				let content = body;
				if (impMatch) {
					importance = parseInt(impMatch[1], 10);
					content = body.slice(impMatch[0].length);
				}
				// Remove strength suffix
				content = content.replace(/\s*\(strength:\s*[\d.]+\)\s*$/, '').trim();

				// Skip auto-generated marker
				if (content.startsWith('Auto-generated')) continue;

				if (content.length > 5) {
					entries.push({ content, type: currentType, importance });
				}
			}
		}

		return entries;
	}

	/**
	 * Check if the MEMORY.md content has changed since last sync.
	 */
	hasChanged(agentId: string, markdown: string): boolean {
		const hash = this._simpleHash(markdown);
		const lastHash = this._lastSyncHash.get(agentId);
		if (hash === lastHash) return false;
		this._lastSyncHash.set(agentId, hash);
		return true;
	}

	private _simpleHash(str: string): string {
		let hash = 0;
		for (let i = 0; i < str.length; i++) {
			const char = str.charCodeAt(i);
			hash = ((hash << 5) - hash) + char;
			hash = hash & hash;
		}
		return Math.abs(hash).toString(16);
	}
}
