/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const AUDIO_ACE_STEP_V1_SONG: StageWorkflowConfig = {
    api_json: {
        "40": {
            "class_type": "CheckpointLoaderSimple",
            "inputs": {
                "ckpt_name": "ace_step_v1_3.5b.safetensors",
            },
        },
        "18": {
            "class_type": "VAEDecodeAudio",
            "inputs": {
                "samples": [
                    "52",
                    0,
                ],
                "vae": [
                    "40",
                    2,
                ],
            },
        },
        "44": {
            "class_type": "ConditioningZeroOut",
            "inputs": {
                "conditioning": [
                    "14",
                    0,
                ],
            },
        },
        "50": {
            "class_type": "LatentOperationTonemapReinhard",
            "inputs": {
                "multiplier": 1.0000000000000002,
            },
        },
        "17": {
            "class_type": "EmptyAceStepLatentAudio",
            "inputs": {
                "seconds": 120,
                "batch_size": 1,
            },
        },
        "49": {
            "class_type": "LatentApplyOperationCFG",
            "inputs": {
                "model": [
                    "51",
                    0,
                ],
                "operation": [
                    "50",
                    0,
                ],
            },
        },
        "52": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "49",
                    0,
                ],
                "positive": [
                    "14",
                    0,
                ],
                "negative": [
                    "44",
                    0,
                ],
                "latent_image": [
                    "17",
                    0,
                ],
                "seed": 468254064217846,
                "steps": 50,
                "cfg": 5,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1,
            },
        },
        "51": {
            "class_type": "ModelSamplingSD3",
            "inputs": {
                "model": [
                    "40",
                    0,
                ],
                "shift": undefined,
            },
        },
        "59": {
            "class_type": "SaveAudioMP3",
            "inputs": {
                "audio": [
                    "18",
                    0,
                ],
                "filename_prefix": "audio/ComfyUI",
                "quality": "V0",
            },
        },
        "14": {
            "class_type": "TextEncodeAceStepAudio",
            "inputs": {
                "clip": [
                    "40",
                    1,
                ],
                "tags": "anime, soft female vocals, kawaii pop, j-pop, childish, piano, guitar, synthesizer, fast, happy, cheerful, lighthearted\t\n",
                "lyrics": "Verse\nNeon rain on my screen,\nDreams compile in silver sheen.\nNo weight, just motion,\nI’m plugged into emotion.\n\nChorus\nComfy Cloud — breathing light,\nCode and color, spark and wire.\nDrift through data, feel alive,\nIn your circuits, I arrive.",
                "lyrics_strength": 0.9900000000000002,
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "59",
    },
    inputs: {
        "14": {
            "lyrics": {
                "from": "option:lyrics",
                "default": "",
                "required": false,
            },
            "tags": {
                "from": "main_prompt",
                "default": "soft female vocals, kawaii pop, j-pop, piano, guitar, synthesizer, cheerful",
                "required": false,
            },
        },
        "17": {
            "seconds": {
                "from": "option:duration_s",
                "default": 120,
                "required": false,
                "cast": "float",
            },
        },
        "40": {
            "ckpt_name": {
                "from": "literal:ace_step_v1_3.5b.safetensors",
                "required": false,
            },
        },
        "52": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
    },
};

export const AUDIO_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "ACE-Step v1 Song": AUDIO_ACE_STEP_V1_SONG,
};
