/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const CUTOUT_BIREFNET_CUTOUT: StageWorkflowConfig = {
    api_json: {
        "17": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "the_lily_veil.png",
            },
        },
        "19": {
            "class_type": "SarosBiRefNetCutout",
            "inputs": {
                "image": [
                    "17",
                    0,
                ],
                // 部署源：D:\ComfyUI\custom_nodes\saros_cutout（本仓库
                // scripts/comfy-custom-nodes/saros_cutout）。模型列表是运行时
                // 枚举 ~/.vssaros/cutout-models 得到的，这里写死 full@1024 与
                // 默认值一致；若该机未装 onnxruntime-gpu 节点会自动退回 CPU EP。
                "model": "BiRefNet-general-epoch_244.onnx",
            },
        },
        "18": {
            "class_type": "SaveImage",
            "inputs": {
                "filename_prefix": "ComfyUI",
                "images": [
                    "19",
                    0,
                ],
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "18",
    },
    inputs: {
        "17": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Cutout needs an upstream image — wire one into this stage's image input.",
            },
        },
    },
};

export const CUTOUT_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "BiRefNet Cutout": CUTOUT_BIREFNET_CUTOUT,
};
