/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const ERASE_LAMA_ERASE: StageWorkflowConfig = {
    api_json: {
        "1": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "2": {
            "class_type": "LoadImageMask",
            "inputs": {
                "image": "example.png",
                "channel": "alpha",
            },
        },
        "6": {
            "class_type": "SaveImage",
            "inputs": {
                "filename_prefix": "ComfyUI",
                "images": [
                    "5",
                    0,
                ],
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "6",
    },
    inputs: {
        "1": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Erase needs an upstream image — wire one into the stage's image input.",
            },
        },
        "2": {
            "channel": {
                "from": "literal:alpha",
                "required": false,
            },
            "image": {
                "from": "option:mask_data",
                "required": true,
                "error": "Erase needs a mask — paint over the area you want to remove before running.",
            },
        },
    },
};

export const ERASE_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "LaMa Erase": ERASE_LAMA_ERASE,
};
