/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const IMAGE_LOCAL_SD1_5: StageWorkflowConfig = {
    api_json: {
        "3": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "4",
                    0,
                ],
                "positive": [
                    "6",
                    0,
                ],
                "negative": [
                    "7",
                    0,
                ],
                "latent_image": [
                    "5",
                    0,
                ],
                "seed": 685468484323813,
                "steps": 20,
                "cfg": 7,
                "sampler_name": "euler",
                "scheduler": "normal",
                "denoise": 1.0,
            },
        },
        "4": {
            "class_type": "CheckpointLoaderSimple",
            "inputs": {
                "ckpt_name": "sd_xl_base_1.0.safetensors",
            },
        },
        "5": {
            "class_type": "EmptyLatentImage",
            "inputs": {
                "width": 1024,
                "height": 1024,
                "batch_size": 1,
            },
        },
        "6": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "4",
                    1,
                ],
                "text": "a red apple on a wooden table",
            },
        },
        "7": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "4",
                    1,
                ],
                "text": "blurry, watermark",
            },
        },
        "8": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    2,
                ],
            },
        },
        "9": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "8",
                    0,
                ],
                "filename_prefix": "SD1.5",
            },
        },
    },
    result: {
        "type": "ui_save_batch",
        "node": "9",
    },
    inputs: {
        "6": {
            "text": {
                "from": "main_prompt",
                "required": false,
            },
        },
    },
};

export const IMAGE_LOCAL_SD1_5_I2I: StageWorkflowConfig = {
    api_json: {
        "4": {
            "class_type": "CheckpointLoaderSimple",
            "inputs": {
                "ckpt_name": "v1-5-pruned-emaonly-fp16.safetensors",
            },
        },
        "10": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "11": {
            "class_type": "VAEEncode",
            "inputs": {
                "pixels": [
                    "10",
                    0,
                ],
                "vae": [
                    "4",
                    2,
                ],
            },
        },
        "6": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "4",
                    1,
                ],
                "text": "a stylised version of the input image, vibrant colors, high detail",
            },
        },
        "7": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "4",
                    1,
                ],
                "text": "text, watermark, low quality",
            },
        },
        "3": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "4",
                    0,
                ],
                "positive": [
                    "6",
                    0,
                ],
                "negative": [
                    "7",
                    0,
                ],
                "latent_image": [
                    "11",
                    0,
                ],
                "seed": 685468484323813,
                "steps": 20,
                "cfg": 8,
                "sampler_name": "euler",
                "scheduler": "normal",
                "denoise": 0.75,
            },
        },
        "8": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    2,
                ],
            },
        },
        "9": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "8",
                    0,
                ],
                "filename_prefix": "ComfyTV/sd15-i2i",
            },
        },
    },
    result: {
        "type": "ui_save_batch",
        "node": "9",
    },
    inputs: {
        "10": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Image-to-image needs an upstream image — wire one into the stage's images input.",
            },
        },
        "3": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "6": {
            "text": {
                "from": "main_prompt",
                "default": "a stylised version of the input image",
                "required": false,
            },
        },
    },
};

export const IMAGE_IMAGE_IDEOGRAM4_T2I: StageWorkflowConfig = {
    api_json: {
        "158": {
            "class_type": "SaveImage",
            "inputs": {
                "filename_prefix": "Ideogram_4.0",
                "images": [
                    "98",
                    0,
                ],
            },
        },
    },
    result: {
        "type": "ui_save_batch",
        "node": "158",
    },
    inputs: {},
};

export const IMAGE_QWEN_PRODUCT_SHOT_CANNY: StageWorkflowConfig = {
    api_json: {
        "123": {
            "class_type": "ResizeImageMaskNode",
            "inputs": {
                "input": [
                    "121",
                    0,
                ],
                "scale_method": "scale total pixels",
            },
        },
        "125": {
            "class_type": "GetImageSize",
            "inputs": {
                "image": [
                    "123",
                    0,
                ],
            },
        },
        "121": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "(pid-72647102).png",
            },
        },
        "60": {
            "class_type": "SaveImage",
            "inputs": {
                "filename_prefix": "Qwen-Image-2512",
                "images": [
                    "86",
                    0,
                ],
            },
        },
        "126": {
            "class_type": "PreviewImage",
            "inputs": {
                "images": [
                    "122",
                    0,
                ],
            },
        },
        "122": {
            "class_type": "Canny",
            "inputs": {
                "image": [
                    "123",
                    0,
                ],
                "low_threshold": 0.33,
                "high_threshold": 0.35,
            },
        },
    },
    result: {
        "type": "ui_save_batch",
        "node": "60",
    },
    inputs: {
        "121": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Product shot needs a reference image — wire a 3D capture (or any image) into the stage.",
            },
        },
    },
};

export const IMAGE_POSE_TRANSFER_SD1_5_IPADAPTER_OPENPOSE: StageWorkflowConfig = {
    api_json: {
        "1": {
            "class_type": "CheckpointLoaderSimple",
            "inputs": {
                "ckpt_name": "DreamShaper_8_pruned.safetensors",
            },
        },
        "2": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "(pid-72684073)荒廃.png",
            },
        },
        "3": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "Gemini_Generated_Image_4in8m74in8m74in8.png",
            },
        },
        "6": {
            "class_type": "CLIPVisionLoader",
            "inputs": {
                "clip_name": "clip_vision_h.safetensors",
            },
        },
        "8": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "1",
                    1,
                ],
                "text": "a person, best quality, highly detailed, sharp focus",
            },
        },
        "9": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "1",
                    1,
                ],
                "text": "lowres, bad anatomy, bad hands, cropped, worst quality, blurry, watermark",
            },
        },
        "10": {
            "class_type": "ControlNetLoader",
            "inputs": {
                "control_net_name": "control_v11p_sd15_openpose_fp16.safetensors",
            },
        },
        "11": {
            "class_type": "ControlNetApplyAdvanced",
            "inputs": {
                "positive": [
                    "8",
                    0,
                ],
                "negative": [
                    "9",
                    0,
                ],
                "control_net": [
                    "10",
                    0,
                ],
                "vae": [
                    "1",
                    2,
                ],
                "image": [
                    "4",
                    0,
                ],
                "strength": undefined,
                "start_percent": undefined,
                "end_percent": undefined,
            },
        },
        "12": {
            "class_type": "EmptyLatentImage",
            "inputs": {
                "width": 512,
                "height": 768,
                "batch_size": 1,
            },
        },
        "13": {
            "class_type": "KSampler",
            "inputs": {
                "positive": [
                    "11",
                    0,
                ],
                "negative": [
                    "11",
                    1,
                ],
                "latent_image": [
                    "12",
                    0,
                ],
                "seed": 0,
                "steps": "fixed",
                "cfg": 25,
                "sampler_name": 7,
                "scheduler": "dpmpp_2m",
                "denoise": "karras",
                "model": [
                    "7",
                    0,
                ],
            },
        },
        "14": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "13",
                    0,
                ],
                "vae": [
                    "1",
                    2,
                ],
            },
        },
        "15": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "14",
                    0,
                ],
                "filename_prefix": "ComfyTV/pose-transfer",
            },
        },
    },
    result: {
        "type": "ui_save_batch",
        "node": "15",
    },
    inputs: {
        "1": {
            "ckpt_name": {
                "from": "literal:DreamShaper_8_pruned.safetensors",
                "required": false,
            },
        },
        "10": {
            "control_net_name": {
                "from": "literal:control_v11p_sd15_openpose_fp16.safetensors",
                "required": false,
            },
        },
        "12": {
            "batch_size": {
                "from": "option:batch_size",
                "default": 1,
                "required": false,
                "cast": "int",
            },
            "height": {
                "from": "computed:height",
                "required": false,
                "cast": "int",
            },
            "width": {
                "from": "computed:width",
                "required": false,
                "cast": "int",
            },
        },
        "13": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "2": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Pose Transfer needs a subject image — wire the original into the stage's image[0] input.",
            },
        },
        "3": {
            "image": {
                "from": "upstream_image:annotated[1]",
                "required": true,
                "error": "Pose Transfer needs an action-reference image — wire a pose reference into the stage's image[1] input.",
            },
        },
        "6": {
            "clip_name": {
                "from": "literal:clip_vision_h.safetensors",
                "required": false,
            },
        },
        "8": {
            "text": {
                "from": "main_prompt",
                "default": "a person, best quality, highly detailed, sharp focus",
                "required": false,
            },
        },
    },
};

export const IMAGE_FLUX2_KLEIN_RELIGHT: StageWorkflowConfig = {
    api_json: {
        "1": {
            "class_type": "KSamplerSelect",
            "inputs": {
                "sampler_name": "euler",
            },
        },
        "2": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "13",
                    0,
                ],
                "text": "",
            },
        },
        "3": {
            "class_type": "EmptyFlux2LatentImage",
            "inputs": {
                "width": [
                    "18",
                    0,
                ],
                "height": [
                    "18",
                    1,
                ],
                "batch_size": 1,
            },
        },
        "4": {
            "class_type": "CFGGuider",
            "inputs": {
                "model": [
                    "23",
                    0,
                ],
                "positive": [
                    "9",
                    0,
                ],
                "negative": [
                    "7",
                    0,
                ],
                "cfg": 1,
            },
        },
        "5": {
            "class_type": "ReferenceLatent",
            "inputs": {
                "conditioning": [
                    "2",
                    0,
                ],
                "latent": [
                    "10",
                    0,
                ],
            },
        },
        "6": {
            "class_type": "SamplerCustomAdvanced",
            "inputs": {
                "noise": [
                    "22",
                    0,
                ],
                "guider": [
                    "4",
                    0,
                ],
                "sampler": [
                    "1",
                    0,
                ],
                "sigmas": [
                    "17",
                    0,
                ],
                "latent_image": [
                    "3",
                    0,
                ],
            },
        },
        "7": {
            "class_type": "ReferenceLatent",
            "inputs": {
                "conditioning": [
                    "5",
                    0,
                ],
                "latent": [
                    "11",
                    0,
                ],
            },
        },
        "8": {
            "class_type": "ReferenceLatent",
            "inputs": {
                "conditioning": [
                    "16",
                    0,
                ],
                "latent": [
                    "10",
                    0,
                ],
            },
        },
        "9": {
            "class_type": "ReferenceLatent",
            "inputs": {
                "conditioning": [
                    "8",
                    0,
                ],
                "latent": [
                    "11",
                    0,
                ],
            },
        },
        "10": {
            "class_type": "VAEEncode",
            "inputs": {
                "pixels": [
                    "25",
                    0,
                ],
                "vae": [
                    "14",
                    0,
                ],
            },
        },
        "11": {
            "class_type": "VAEEncode",
            "inputs": {
                "pixels": [
                    "30",
                    0,
                ],
                "vae": [
                    "14",
                    0,
                ],
            },
        },
        "12": {
            "class_type": "UNETLoader",
            "inputs": {
                "unet_name": "flux-2-klein-9b-nvfp4.safetensors",
                "weight_dtype": "default",
            },
        },
        "13": {
            "class_type": "CLIPLoader",
            "inputs": {
                "clip_name": "qwen_3_8b_fp8mixed.safetensors",
                "type": "flux2",
            },
        },
        "14": {
            "class_type": "VAELoader",
            "inputs": {
                "vae_name": "flux2-vae.safetensors",
            },
        },
        "15": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "6",
                    0,
                ],
                "vae": [
                    "14",
                    0,
                ],
            },
        },
        "16": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "13",
                    0,
                ],
                "text": " match the sun direction from the reference",
            },
        },
        "17": {
            "class_type": "Flux2Scheduler",
            "inputs": {
                "width": [
                    "18",
                    0,
                ],
                "height": [
                    "18",
                    1,
                ],
                "steps": 4,
            },
        },
        "18": {
            "class_type": "GetImageSize",
            "inputs": {
                "image": [
                    "25",
                    0,
                ],
            },
        },
        "22": {
            "class_type": "RandomNoise",
            "inputs": {
                "noise_seed": 641563518514615,
            },
        },
        "23": {
            "class_type": "LoraLoaderModelOnly",
            "inputs": {
                "model": [
                    "12",
                    0,
                ],
                "lora_name": 1,
                "strength_model": undefined,
            },
        },
        "25": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "12.png",
            },
        },
        "28": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "15",
                    0,
                ],
                "filename_prefix": "ComfyUI",
            },
        },
        "30": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "(pid-66823055)Ã¦_Â³Ã£__Ã£__Ã£_Â¯Ã£__Ã£__Ã¥Â¦_Ã¥Â¤Â¢Ã£_Â¡Ã£__Ã£__.jpg",
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "28",
    },
    inputs: {
        "16": {
            "text": {
                "from": "main_prompt",
                "default": "match the sun direction from the reference",
                "required": false,
            },
        },
        "2": {
            "text": {
                "from": "option:negative",
                "default": "",
                "required": false,
            },
        },
        "22": {
            "noise_seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "25": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Relight needs a subject image — wire one into the stage's first image slot.",
            },
        },
        "30": {
            "image": {
                "from": "upstream_image:annotated[1]",
                "required": true,
                "error": "Relight needs a lighting reference in the 2nd image slot — wire the Relight node's '3d light' output (or any image) into it.",
            },
        },
    },
};

export const IMAGE_QWEN_2512_T2I: StageWorkflowConfig = {
    // ★ 本地 qwen-image-2512 文生图（白底贴纸风格），用于「qwen 图 → 表情包视频」链路的第一环。
    //   已本机验证：qwen_image_2512_fp8_e4m3fn + EmptySD3LatentImage 出 1 张清晰图（30s）。
    //   ⚠ 关键：qwen_image_2512 是【非分层】模型（model_detection.py:936-939 只有 2511 才是
    //     Layered），必须用 EmptySD3LatentImage（16 通道单层）；若误用
    //     EmptyQwenImageLayeredLatentImage（layers=3）会通道数不匹配 → 模型把多层当多张图
    //     输出（13 张混乱图）。其余接线与 Flux 类似（ModelSamplingAuraFlow shift=1.73）。
    api_json: {
        "1": {
            "class_type": "UNETLoader",
            "inputs": {
                "unet_name": "qwen_image_2512_fp8_e4m3fn.safetensors",
                "weight_dtype": "default",
            },
        },
        "2": {
            "class_type": "ModelSamplingAuraFlow",
            "inputs": {
                "model": ["1", 0],
                "shift": 1.73,
            },
        },
        "3": {
            "class_type": "CLIPLoader",
            "inputs": {
                "clip_name": "qwen_2.5_vl_7b_fp8_scaled.safetensors",
                "type": "qwen_image",
            },
        },
        "4": {
            "class_type": "VAELoader",
            "inputs": {
                "vae_name": "qwen_image_vae.safetensors",
            },
        },
        "5": {
            "class_type": "TextEncodeQwenImageEdit",
            "inputs": {
                "clip": ["3", 0],
                "prompt": "a cute round cartoon bird, sticker style",
            },
        },
        "6": {
            "class_type": "EmptySD3LatentImage",
            "inputs": {
                "width": 768,
                "height": 768,
                "batch_size": 1,
            },
        },
        "7": {
            "class_type": "RandomNoise",
            "inputs": {
                "noise_seed": 12345,
            },
        },
        "8": {
            "class_type": "KSamplerSelect",
            "inputs": {
                "sampler_name": "euler",
            },
        },
        "9": {
            "class_type": "BasicScheduler",
            "inputs": {
                "model": ["2", 0],
                "scheduler": "simple",
                "steps": 20,
                "denoise": 1,
            },
        },
        "10": {
            "class_type": "BasicGuider",
            "inputs": {
                "model": ["2", 0],
                "conditioning": ["5", 0],
            },
        },
        "11": {
            "class_type": "SamplerCustomAdvanced",
            "inputs": {
                "noise": ["7", 0],
                "guider": ["10", 0],
                "sampler": ["8", 0],
                "sigmas": ["9", 0],
                "latent_image": ["6", 0],
            },
        },
        "12": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": ["11", 0],
                "vae": ["4", 0],
            },
        },
        "13": {
            "class_type": "SaveImage",
            "inputs": {
                "images": ["12", 0],
                "filename_prefix": "Qwen-Image-2512",
            },
        },
    },
    result: {
        "type": "ui_save_batch",
        "node": "13",
    },
    inputs: {
        "5": {
            "prompt": {
                "from": "main_prompt",
                "required": true,
                "error": "Qwen 2512 T2I needs a prompt.",
            },
        },
        "7": {
            "noise_seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
    },
};

export const IMAGE_QWEN_2512_MULTI_PANEL: StageWorkflowConfig = {
    // ★ 本地 qwen-image-2512 多宫格漫画（单图直出 N 宫格，纯 prompt 驱动）。
    //   Qwen-Image 经多图一致性训练，靠 prompt 描述宫格布局即可单张直出。
    //   宫格数由 grid_count widget 动态注入（prefix 的 {{grid_count}} 占位符，
    //   见 stageWorkflowExecutor.interpolateBindingTemplate）。分辨率用官方推荐
    //   1328²（1:1），比默认 768² 高、单格细节更足。其余接线与 IMAGE_QWEN_2512_T2I
    //   完全一致（qwen_image_2512 非分层模型 → EmptySD3LatentImage 16 通道单层）。
    api_json: {
        "1": {
            "class_type": "UNETLoader",
            "inputs": {
                "unet_name": "qwen_image_2512_fp8_e4m3fn.safetensors",
                "weight_dtype": "default",
            },
        },
        "2": {
            "class_type": "ModelSamplingAuraFlow",
            "inputs": {
                "model": ["1", 0],
                "shift": 1.73,
            },
        },
        "3": {
            "class_type": "CLIPLoader",
            "inputs": {
                "clip_name": "qwen_2.5_vl_7b_fp8_scaled.safetensors",
                "type": "qwen_image",
            },
        },
        "4": {
            "class_type": "VAELoader",
            "inputs": {
                "vae_name": "qwen_image_vae.safetensors",
            },
        },
        "5": {
            "class_type": "TextEncodeQwenImageEdit",
            "inputs": {
                "clip": ["3", 0],
                "prompt": "4宫格漫画，2×2排列，等宽白色边框，不要文字",
            },
        },
        "6": {
            "class_type": "EmptySD3LatentImage",
            "inputs": {
                "width": 1328,
                "height": 1328,
                "batch_size": 1,
            },
        },
        "7": {
            "class_type": "RandomNoise",
            "inputs": {
                "noise_seed": 12345,
            },
        },
        "8": {
            "class_type": "KSamplerSelect",
            "inputs": {
                "sampler_name": "euler",
            },
        },
        "9": {
            "class_type": "BasicScheduler",
            "inputs": {
                "model": ["2", 0],
                "scheduler": "simple",
                "steps": 20,
                "denoise": 1,
            },
        },
        "10": {
            "class_type": "BasicGuider",
            "inputs": {
                "model": ["2", 0],
                "conditioning": ["5", 0],
            },
        },
        "11": {
            "class_type": "SamplerCustomAdvanced",
            "inputs": {
                "noise": ["7", 0],
                "guider": ["10", 0],
                "sampler": ["8", 0],
                "sigmas": ["9", 0],
                "latent_image": ["6", 0],
            },
        },
        "12": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": ["11", 0],
                "vae": ["4", 0],
            },
        },
        "13": {
            "class_type": "SaveImage",
            "inputs": {
                "images": ["12", 0],
                "filename_prefix": "Qwen-Image-2512-multipanel",
            },
        },
    },
    result: {
        "type": "ui_save_batch",
        "node": "13",
    },
    inputs: {
        "5": {
            "prompt": {
                "from": "main_prompt",
                "required": true,
                "prefix": "{{grid_count}}宫格漫画，等宽白色边框，不要文字。\n\n",
                "default": "角色：年轻男性，黑色短发，圆脸，戴银色圆框眼镜，穿深蓝色夹克、白色T恤，暖色室内光。\n第1格：正面站立，微笑。\n第2格：侧面转头，惊讶。\n第3格：坐在地上，低头思考。\n第4格：背对镜头，看向窗外。",
                "suffix": "\n\n一致性要求：所有宫格为同一角色、同一服装、同一光线，统一画面风格。",
                "error": "Qwen 2512 多宫格 needs a prompt (role + per-panel content).",
            },
        },
        "7": {
            "noise_seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
    },
};

export const IMAGE_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "Local SD1.5": IMAGE_LOCAL_SD1_5,
    "Local SD1.5 I2I": IMAGE_LOCAL_SD1_5_I2I,
    "Image Ideogram4 T2I": IMAGE_IMAGE_IDEOGRAM4_T2I,
    "Qwen Product Shot (Canny)": IMAGE_QWEN_PRODUCT_SHOT_CANNY,
    "Qwen 2512 T2I": IMAGE_QWEN_2512_T2I,
    "Qwen 2512 多宫格": IMAGE_QWEN_2512_MULTI_PANEL,
    "Pose Transfer (SD1.5 IPAdapter + OpenPose)": IMAGE_POSE_TRANSFER_SD1_5_IPADAPTER_OPENPOSE,
    "Flux2 Klein Relight": IMAGE_FLUX2_KLEIN_RELIGHT,
};
