/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const IMAGE_EDIT_QWEN_EDIT_2511: StageWorkflowConfig = {
    api_json: {
        "1": {
            "class_type": "UNETLoader",
            "inputs": {
                "unet_name": "qwen_image_edit_2511_fp8mixed.safetensors",
                "weight_dtype": "default",
            },
        },
        "2": {
            "class_type": "CLIPLoader",
            "inputs": {
                "clip_name": "qwen_2.5_vl_7b_fp8_scaled.safetensors",
                "type": "qwen_image",
            },
        },
        "3": {
            "class_type": "VAELoader",
            "inputs": {
                "vae_name": "qwen_image_vae.safetensors",
            },
        },
        "4": {
            "class_type": "LoraLoaderModelOnly",
            "inputs": {
                "model": [
                    "1",
                    0,
                ],
                "lora_name": 1.0,
                "strength_model": undefined,
            },
        },
        "5": {
            "class_type": "ModelSamplingAuraFlow",
            "inputs": {
                "model": [
                    "4",
                    0,
                ],
                "shift": undefined,
            },
        },
        "6": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "7": {
            "class_type": "ImageScaleToTotalPixels",
            "inputs": {
                "image": [
                    "6",
                    0,
                ],
                "upscale_method": "lanczos",
                "megapixels": 1.0,
                "resolution_steps": 8,
            },
        },
        "8": {
            "class_type": "VAEEncode",
            "inputs": {
                "pixels": [
                    "7",
                    0,
                ],
                "vae": [
                    "3",
                    0,
                ],
            },
        },
        "9": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "2",
                    0,
                ],
                "vae": [
                    "3",
                    0,
                ],
                "image1": [
                    "7",
                    0,
                ],
                "prompt": "",
            },
        },
        "10": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "2",
                    0,
                ],
                "vae": [
                    "3",
                    0,
                ],
                "prompt": "",
            },
        },
        "11": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "5",
                    0,
                ],
                "positive": [
                    "9",
                    0,
                ],
                "negative": [
                    "10",
                    0,
                ],
                "latent_image": [
                    "8",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "12": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "11",
                    0,
                ],
                "vae": [
                    "3",
                    0,
                ],
            },
        },
        "13": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "12",
                    0,
                ],
                "filename_prefix": "comfytv-edit",
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "13",
    },
    inputs: {
        "11": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "6": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Image edit needs an upstream image — wire one into the stage's image input.",
            },
        },
        "9": {
            "prompt": {
                "from": "main_prompt",
                "required": true,
                "error": "Describe the edit — e.g. 'turn this render into a product photo on a light-gray studio backdrop, keep the subject's colors and materials'.",
            },
        },
    },
};

export const IMAGE_EDIT_FLUX_CANNY_EDIT: StageWorkflowConfig = {
    api_json: {
        "34": {
            "class_type": "DualCLIPLoader",
            "inputs": {
                "clip_name1": "clip_l.safetensors",
                "clip_name2": "t5xxl_fp8_e4m3fn_scaled.safetensors",
                "type": "flux",
            },
        },
        "37": {
            "class_type": "ConditioningZeroOut",
            "inputs": {
                "conditioning": [
                    "23",
                    0,
                ],
            },
        },
        "31": {
            "class_type": "UNETLoader",
            "inputs": {
                "unet_name": "flux1-canny-dev.safetensors",
                "weight_dtype": "default",
            },
        },
        "32": {
            "class_type": "VAELoader",
            "inputs": {
                "vae_name": "ae.safetensors",
            },
        },
        "26": {
            "class_type": "FluxGuidance",
            "inputs": {
                "conditioning": [
                    "23",
                    0,
                ],
                "guidance": 30,
            },
        },
        "18": {
            "class_type": "Canny",
            "inputs": {
                "image": [
                    "17",
                    0,
                ],
                "low_threshold": 0.15,
                "high_threshold": 0.3,
            },
        },
        "17": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "flux_canny_model_example_input_image.png",
            },
        },
        "9": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "8",
                    0,
                ],
                "filename_prefix": "ComfyUI",
            },
        },
        "8": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "3",
                    0,
                ],
                "vae": [
                    "32",
                    0,
                ],
            },
        },
        "3": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "31",
                    0,
                ],
                "positive": [
                    "35",
                    0,
                ],
                "negative": [
                    "35",
                    1,
                ],
                "latent_image": [
                    "35",
                    2,
                ],
                "seed": 1125476660951871,
                "steps": 20,
                "cfg": 1,
                "sampler_name": "euler",
                "scheduler": "normal",
                "denoise": 1,
            },
        },
        "35": {
            "class_type": "InstructPixToPixConditioning",
            "inputs": {
                "positive": [
                    "26",
                    0,
                ],
                "negative": [
                    "37",
                    0,
                ],
                "vae": [
                    "32",
                    0,
                ],
                "pixels": [
                    "18",
                    0,
                ],
            },
        },
        "19": {
            "class_type": "PreviewImage",
            "inputs": {
                "images": [
                    "18",
                    0,
                ],
            },
        },
        "23": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "34",
                    0,
                ],
                "text": "A vibrant red ladybug rests on a blooming deep purple rose with lush, velvety petals. The background is a soft pink, filled with subtly blurred roses of the same pink shade, creating a dreamy and romantic atmosphere.",
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "9",
    },
    inputs: {
        "17": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Flux Canny needs an upstream image — wire one into the stage's image input.",
            },
        },
        "23": {
            "text": {
                "from": "main_prompt",
                "default": "A vibrant red ladybug rests on a blooming deep purple rose with lush, velvety petals.",
                "required": false,
            },
        },
        "3": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "31": {
            "unet_name": {
                "from": "literal:flux1-canny-dev_fp8.safetensors",
                "required": false,
            },
        },
        "32": {
            "vae_name": {
                "from": "literal:ae.safetensors",
                "required": false,
            },
        },
        "34": {
            "clip_name1": {
                "from": "literal:clip_l.safetensors",
                "required": false,
            },
            "clip_name2": {
                "from": "literal:t5xxl_fp8_e4m3fn_scaled.safetensors",
                "required": false,
            },
        },
    },
};

export const IMAGE_EDIT_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "Qwen Edit 2511": IMAGE_EDIT_QWEN_EDIT_2511,
    "Flux Canny Edit": IMAGE_EDIT_FLUX_CANNY_EDIT,
};
