/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const INPAINT_FLUX_FILL_INPAINT: StageWorkflowConfig = {
    api_json: {
        "9": {
            "class_type": "SaveImage",
            "inputs": {
                "filename_prefix": "ComfyUI",
                "images": [
                    "47",
                    0,
                ],
            },
        },
        "17": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "flux_fill_inpaint_example_input_image.png",
            },
        },
        "100": {
            "class_type": "LoadImageMask",
            "inputs": {
                "image": "example.png",
                "channel": "alpha",
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "9",
    },
    inputs: {
        "100": {
            "channel": {
                "from": "literal:alpha",
                "required": false,
            },
            "image": {
                "from": "option:mask_data",
                "required": true,
                "error": "Inpaint needs a mask — paint the area you want to change before running.",
            },
        },
        "17": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Inpaint needs an upstream image — wire one into the stage's image input.",
            },
        },
    },
};

export const INPAINT_FOOOCUS_SDXL_INPAINT: StageWorkflowConfig = {
    api_json: {
        "10": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "19",
                    1,
                ],
                "text": "text, watermark",
            },
        },
        "19": {
            "class_type": "CheckpointLoaderSimple",
            "inputs": {
                "ckpt_name": "juggernautXL_version6Rundiffusion.safetensors",
            },
        },
        "14": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "40",
                    0,
                ],
                "vae": [
                    "19",
                    2,
                ],
            },
        },
        "65": {
            "class_type": "ImageCompositeMasked",
            "inputs": {
                "destination": [
                    "33",
                    0,
                ],
                "source": [
                    "14",
                    0,
                ],
                "mask": [
                    "101",
                    0,
                ],
                "x": 0,
                "y": 0,
                "resize_source": false,
            },
        },
        "59": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "65",
                    0,
                ],
                "filename_prefix": "ComfyUI",
            },
        },
        "9": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "19",
                    1,
                ],
                "text": "POSITIVE PROMPT",
            },
        },
        "33": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "base1024.png",
            },
        },
        "40": {
            "class_type": "KSampler",
            "inputs": {
                "seed": 949757093954838,
                "steps": 20,
                "cfg": 5,
                "sampler_name": "dpmpp_2m_sde_gpu",
                "scheduler": "karras",
                "denoise": 0.7000000000000001,
                "model": [
                    "36",
                    0,
                ],
                "positive": [
                    "44",
                    0,
                ],
                "negative": [
                    "44",
                    1,
                ],
                "latent_image": [
                    "44",
                    3,
                ],
            },
        },
        "101": {
            "class_type": "LoadImageMask",
            "inputs": {
                "image": "example.png",
                "channel": "alpha",
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "59",
    },
    inputs: {
        "10": {
            "text": {
                "from": "option:negative",
                "default": "text, watermark, low quality, blurry",
                "required": false,
            },
        },
        "101": {
            "channel": {
                "from": "literal:alpha",
                "required": false,
            },
            "image": {
                "from": "option:mask_data",
                "required": true,
                "error": "Inpaint needs a mask — paint the area you want to change before running.",
            },
        },
        "19": {
            "ckpt_name": {
                "from": "literal:animagine-xl-3.1.safetensors",
                "required": false,
            },
        },
        "33": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Inpaint needs an upstream image — wire one into the stage's image input.",
            },
        },
        "40": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "9": {
            "text": {
                "from": "main_prompt",
                "default": "high-quality, sharp focus, natural lighting",
                "required": false,
            },
        },
    },
};

export const INPAINT_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "Flux Fill Inpaint": INPAINT_FLUX_FILL_INPAINT,
    "Fooocus SDXL Inpaint": INPAINT_FOOOCUS_SDXL_INPAINT,
};
