/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const MATERIAL_ESTIMATE_QWEN3_VL_8B_ESTIMATE: StageWorkflowConfig = {
    api_json: {
        "8": {
            "class_type": "CLIPLoader",
            "inputs": {
                "clip_name": "qwen3vl_8b_fp8_scaled.safetensors",
                "type": "ltxv",
            },
        },
        "2": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "7": {
            "class_type": "TextGenerate",
            "inputs": {
                "clip": [
                    "8",
                    0,
                ],
                "image": [
                    "2",
                    0,
                ],
                "prompt": "You are a 3D material artist. Look at this close-up patch of a product photo and estimate physically-based rendering parameters for the surface material. Respond with ONLY a raw JSON object (no markdown, no explanation) with keys: \"color\" (hex sRGB base color like \"#a1b2c3\"), \"metalness\" (0-1), \"roughness\" (0-1), \"transmission\" (0-1), \"opacity\" (0-1), \"clearcoat\" (0-1), \"ior\" (1.0-2.333). Look carefully: if anything shows through the surface or it looks like glass or translucent plastic, transmission must be high (clear glass ~1.0 with low roughness; frosted/milky ~1.0 with roughness 0.3-0.6). Polished metal means metalness near 1. Only use transmission 0 for fully opaque surfaces.",
                "max_length": 512,
            },
        },
        "5": {
            "class_type": "PreviewAny",
            "inputs": {
                "source": [
                    "7",
                    0,
                ],
            },
        },
    },
    result: {
        "type": "graph_output_first",
        "node": "7",
    },
    inputs: {
        "2": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Material estimation needs an image — wire one into the stage's image input.",
            },
        },
    },
};

export const MATERIAL_ESTIMATE_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "Qwen3-VL 8B Estimate": MATERIAL_ESTIMATE_QWEN3_VL_8B_ESTIMATE,
};
