/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const MULTIVIEW_FACE_3_VIEW: StageWorkflowConfig = {
    api_json: {
        "1": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "5": {
            "class_type": "GetImageSize",
            "inputs": {
                "image": [
                    "1",
                    0,
                ],
            },
        },
        "6": {
            "class_type": "FluxKontextImageScale",
            "inputs": {
                "image": [
                    "1",
                    0,
                ],
            },
        },
        "2": {
            "class_type": "UNETLoader",
            "inputs": {
                "unet_name": "qwen_image_edit_2511_fp8mixed.safetensors",
                "weight_dtype": "default",
            },
        },
        "7": {
            "class_type": "LoraLoaderModelOnly",
            "inputs": {
                "model": [
                    "2",
                    0,
                ],
                "lora_name": 1.0,
                "strength_model": undefined,
            },
        },
        "8": {
            "class_type": "LoraLoaderModelOnly",
            "inputs": {
                "model": [
                    "7",
                    0,
                ],
                "lora_name": 1.0,
                "strength_model": undefined,
            },
        },
        "14": {
            "class_type": "ModelSamplingAuraFlow",
            "inputs": {
                "model": [
                    "8",
                    0,
                ],
                "shift": undefined,
            },
        },
        "19": {
            "class_type": "CFGNorm",
            "inputs": {
                "model": [
                    "14",
                    0,
                ],
                "strength": 1.0,
            },
        },
        "3": {
            "class_type": "CLIPLoader",
            "inputs": {
                "clip_name": "qwen_2.5_vl_7b_fp8_scaled.safetensors",
                "type": "qwen_image",
            },
        },
        "4": {
            "class_type": "VAELoader",
            "inputs": {
                "vae_name": "qwen_image_vae.safetensors",
            },
        },
        "9": {
            "class_type": "VAEEncode",
            "inputs": {
                "pixels": [
                    "6",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "10": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "",
            },
        },
        "15": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "10",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "11": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> front view eye-level shot medium shot, close-up portrait",
            },
        },
        "16": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "11",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "20": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "19",
                    0,
                ],
                "positive": [
                    "16",
                    0,
                ],
                "negative": [
                    "15",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "23": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "20",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "26": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "23",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "29": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "26",
                    0,
                ],
                "filename_prefix": "ComfyTV/face3view-1-front",
            },
        },
        "12": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> right side view eye-level shot medium shot, close-up portrait",
            },
        },
        "17": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "12",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "21": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "19",
                    0,
                ],
                "positive": [
                    "17",
                    0,
                ],
                "negative": [
                    "15",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "24": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "21",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "27": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "24",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "30": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "27",
                    0,
                ],
                "filename_prefix": "ComfyTV/face3view-2-side",
            },
        },
        "13": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> front-right quarter view eye-level shot medium shot, close-up portrait",
            },
        },
        "18": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "13",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "22": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "19",
                    0,
                ],
                "positive": [
                    "18",
                    0,
                ],
                "negative": [
                    "15",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "25": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "22",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "28": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "25",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "31": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "28",
                    0,
                ],
                "filename_prefix": "ComfyTV/face3view-3-quarter",
            },
        },
    },
    result: {
        "type": "ui_save_batch",
        "node": "29",
    },
    inputs: {
        "1": {
            "image": {
                "from": "upstream_image:annotated",
                "required": true,
                "error": "Face 3-View needs an upstream image — wire one into the image slot.",
            },
        },
        "11": {
            "prompt": {
                "from": "main_prompt",
                "default": "a high-quality photograph",
                "prefix": "<sks> front view eye-level shot medium shot, close-up portrait, ",
                "required": false,
            },
        },
        "12": {
            "prompt": {
                "from": "main_prompt",
                "default": "a high-quality photograph",
                "prefix": "<sks> right side view eye-level shot medium shot, close-up portrait, ",
                "required": false,
            },
        },
        "13": {
            "prompt": {
                "from": "main_prompt",
                "default": "a high-quality photograph",
                "prefix": "<sks> front-right quarter view eye-level shot medium shot, close-up portrait, ",
                "required": false,
            },
        },
        "2": {
            "unet_name": {
                "from": "literal:qwen_image_edit_2511_fp8mixed.safetensors",
                "required": false,
            },
        },
        "20": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "21": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "22": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "3": {
            "clip_name": {
                "from": "literal:qwen_2.5_vl_7b_fp8_scaled.safetensors",
                "required": false,
            },
        },
        "4": {
            "vae_name": {
                "from": "literal:qwen_image_vae.safetensors",
                "required": false,
            },
        },
        "7": {
            "lora_name": {
                "from": "literal:qwen-image-edit-2511-multiple-angles-lora.safetensors",
                "required": false,
            },
        },
        "8": {
            "lora_name": {
                "from": "literal:Qwen-Image-Edit-2511-Lightning-4steps-V1.0-bf16.safetensors",
                "required": false,
            },
        },
    },
};

export const MULTIVIEW_PRODUCT_3_VIEW: StageWorkflowConfig = {
    api_json: {
        "1": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "5": {
            "class_type": "GetImageSize",
            "inputs": {
                "image": [
                    "1",
                    0,
                ],
            },
        },
        "6": {
            "class_type": "FluxKontextImageScale",
            "inputs": {
                "image": [
                    "1",
                    0,
                ],
            },
        },
        "2": {
            "class_type": "UNETLoader",
            "inputs": {
                "unet_name": "qwen_image_edit_2511_fp8mixed.safetensors",
                "weight_dtype": "default",
            },
        },
        "7": {
            "class_type": "LoraLoaderModelOnly",
            "inputs": {
                "model": [
                    "2",
                    0,
                ],
                "lora_name": 1.0,
                "strength_model": undefined,
            },
        },
        "8": {
            "class_type": "LoraLoaderModelOnly",
            "inputs": {
                "model": [
                    "7",
                    0,
                ],
                "lora_name": 1.0,
                "strength_model": undefined,
            },
        },
        "14": {
            "class_type": "ModelSamplingAuraFlow",
            "inputs": {
                "model": [
                    "8",
                    0,
                ],
                "shift": undefined,
            },
        },
        "19": {
            "class_type": "CFGNorm",
            "inputs": {
                "model": [
                    "14",
                    0,
                ],
                "strength": 1.0,
            },
        },
        "3": {
            "class_type": "CLIPLoader",
            "inputs": {
                "clip_name": "qwen_2.5_vl_7b_fp8_scaled.safetensors",
                "type": "qwen_image",
            },
        },
        "4": {
            "class_type": "VAELoader",
            "inputs": {
                "vae_name": "qwen_image_vae.safetensors",
            },
        },
        "9": {
            "class_type": "VAEEncode",
            "inputs": {
                "pixels": [
                    "6",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "10": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "",
            },
        },
        "15": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "10",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "11": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> front view eye-level shot medium shot, product photography, isolated subject, clean background",
            },
        },
        "16": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "11",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "20": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "19",
                    0,
                ],
                "positive": [
                    "16",
                    0,
                ],
                "negative": [
                    "15",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "23": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "20",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "26": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "23",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "29": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "26",
                    0,
                ],
                "filename_prefix": "ComfyTV/product3view-1-front",
            },
        },
        "12": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> right side view eye-level shot medium shot, product photography, isolated subject, clean background",
            },
        },
        "17": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "12",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "21": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "19",
                    0,
                ],
                "positive": [
                    "17",
                    0,
                ],
                "negative": [
                    "15",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "24": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "21",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "27": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "24",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "30": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "27",
                    0,
                ],
                "filename_prefix": "ComfyTV/product3view-2-side",
            },
        },
        "13": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> back view eye-level shot medium shot, product photography, isolated subject, clean background",
            },
        },
        "18": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "13",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "22": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "19",
                    0,
                ],
                "positive": [
                    "18",
                    0,
                ],
                "negative": [
                    "15",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "25": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "22",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "28": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "25",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "31": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "28",
                    0,
                ],
                "filename_prefix": "ComfyTV/product3view-3-back",
            },
        },
    },
    result: {
        "type": "ui_save_batch",
        "node": "29",
    },
    inputs: {
        "1": {
            "image": {
                "from": "upstream_image:annotated",
                "required": true,
                "error": "Product 3-View needs an upstream image.",
            },
        },
        "11": {
            "prompt": {
                "from": "main_prompt",
                "default": "a product photograph",
                "prefix": "<sks> front view eye-level shot medium shot, product photography, isolated subject, clean background, ",
                "required": false,
            },
        },
        "12": {
            "prompt": {
                "from": "main_prompt",
                "default": "a product photograph",
                "prefix": "<sks> right side view eye-level shot medium shot, product photography, isolated subject, clean background, ",
                "required": false,
            },
        },
        "13": {
            "prompt": {
                "from": "main_prompt",
                "default": "a product photograph",
                "prefix": "<sks> back view eye-level shot medium shot, product photography, isolated subject, clean background, ",
                "required": false,
            },
        },
        "2": {
            "unet_name": {
                "from": "literal:qwen_image_edit_2511_fp8mixed.safetensors",
                "required": false,
            },
        },
        "20": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "21": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "22": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "3": {
            "clip_name": {
                "from": "literal:qwen_2.5_vl_7b_fp8_scaled.safetensors",
                "required": false,
            },
        },
        "4": {
            "vae_name": {
                "from": "literal:qwen_image_vae.safetensors",
                "required": false,
            },
        },
        "7": {
            "lora_name": {
                "from": "literal:qwen-image-edit-2511-multiple-angles-lora.safetensors",
                "required": false,
            },
        },
        "8": {
            "lora_name": {
                "from": "literal:Qwen-Image-Edit-2511-Lightning-4steps-V1.0-bf16.safetensors",
                "required": false,
            },
        },
    },
};

export const MULTIVIEW_CHARACTER_3_VIEW: StageWorkflowConfig = {
    api_json: {
        "1": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "5": {
            "class_type": "GetImageSize",
            "inputs": {
                "image": [
                    "1",
                    0,
                ],
            },
        },
        "6": {
            "class_type": "FluxKontextImageScale",
            "inputs": {
                "image": [
                    "1",
                    0,
                ],
            },
        },
        "2": {
            "class_type": "UNETLoader",
            "inputs": {
                "unet_name": "qwen_image_edit_2511_fp8mixed.safetensors",
                "weight_dtype": "default",
            },
        },
        "7": {
            "class_type": "LoraLoaderModelOnly",
            "inputs": {
                "model": [
                    "2",
                    0,
                ],
                "lora_name": 1.0,
                "strength_model": undefined,
            },
        },
        "8": {
            "class_type": "LoraLoaderModelOnly",
            "inputs": {
                "model": [
                    "7",
                    0,
                ],
                "lora_name": 1.0,
                "strength_model": undefined,
            },
        },
        "14": {
            "class_type": "ModelSamplingAuraFlow",
            "inputs": {
                "model": [
                    "8",
                    0,
                ],
                "shift": undefined,
            },
        },
        "19": {
            "class_type": "CFGNorm",
            "inputs": {
                "model": [
                    "14",
                    0,
                ],
                "strength": 1.0,
            },
        },
        "3": {
            "class_type": "CLIPLoader",
            "inputs": {
                "clip_name": "qwen_2.5_vl_7b_fp8_scaled.safetensors",
                "type": "qwen_image",
            },
        },
        "4": {
            "class_type": "VAELoader",
            "inputs": {
                "vae_name": "qwen_image_vae.safetensors",
            },
        },
        "9": {
            "class_type": "VAEEncode",
            "inputs": {
                "pixels": [
                    "6",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "10": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "",
            },
        },
        "15": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "10",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "11": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> front view eye-level shot wide shot, full body, character reference sheet",
            },
        },
        "16": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "11",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "20": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "19",
                    0,
                ],
                "positive": [
                    "16",
                    0,
                ],
                "negative": [
                    "15",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "23": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "20",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "26": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "23",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "29": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "26",
                    0,
                ],
                "filename_prefix": "ComfyTV/char3view-1-front",
            },
        },
        "12": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> right side view eye-level shot wide shot, full body, character reference sheet",
            },
        },
        "17": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "12",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "21": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "19",
                    0,
                ],
                "positive": [
                    "17",
                    0,
                ],
                "negative": [
                    "15",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "24": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "21",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "27": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "24",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "30": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "27",
                    0,
                ],
                "filename_prefix": "ComfyTV/char3view-2-side",
            },
        },
        "13": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> back view eye-level shot wide shot, full body, character reference sheet",
            },
        },
        "18": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "13",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "22": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "19",
                    0,
                ],
                "positive": [
                    "18",
                    0,
                ],
                "negative": [
                    "15",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "25": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "22",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "28": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "25",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "31": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "28",
                    0,
                ],
                "filename_prefix": "ComfyTV/char3view-3-back",
            },
        },
    },
    result: {
        "type": "ui_save_batch",
        "node": "29",
    },
    inputs: {
        "1": {
            "image": {
                "from": "upstream_image:annotated",
                "required": true,
                "error": "Character 3-View needs an upstream image.",
            },
        },
        "11": {
            "prompt": {
                "from": "main_prompt",
                "default": "a character",
                "prefix": "<sks> front view eye-level shot wide shot, full body, character reference sheet, ",
                "required": false,
            },
        },
        "12": {
            "prompt": {
                "from": "main_prompt",
                "default": "a character",
                "prefix": "<sks> right side view eye-level shot wide shot, full body, character reference sheet, ",
                "required": false,
            },
        },
        "13": {
            "prompt": {
                "from": "main_prompt",
                "default": "a character",
                "prefix": "<sks> back view eye-level shot wide shot, full body, character reference sheet, ",
                "required": false,
            },
        },
        "2": {
            "unet_name": {
                "from": "literal:qwen_image_edit_2511_fp8mixed.safetensors",
                "required": false,
            },
        },
        "20": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "21": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "22": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "3": {
            "clip_name": {
                "from": "literal:qwen_2.5_vl_7b_fp8_scaled.safetensors",
                "required": false,
            },
        },
        "4": {
            "vae_name": {
                "from": "literal:qwen_image_vae.safetensors",
                "required": false,
            },
        },
        "7": {
            "lora_name": {
                "from": "literal:qwen-image-edit-2511-multiple-angles-lora.safetensors",
                "required": false,
            },
        },
        "8": {
            "lora_name": {
                "from": "literal:Qwen-Image-Edit-2511-Lightning-4steps-V1.0-bf16.safetensors",
                "required": false,
            },
        },
    },
};

export const MULTIVIEW_MULTI_CAM_9: StageWorkflowConfig = {
    api_json: {
        "1": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "5": {
            "class_type": "GetImageSize",
            "inputs": {
                "image": [
                    "1",
                    0,
                ],
            },
        },
        "6": {
            "class_type": "FluxKontextImageScale",
            "inputs": {
                "image": [
                    "1",
                    0,
                ],
            },
        },
        "2": {
            "class_type": "UNETLoader",
            "inputs": {
                "unet_name": "qwen_image_edit_2511_fp8mixed.safetensors",
                "weight_dtype": "default",
            },
        },
        "7": {
            "class_type": "LoraLoaderModelOnly",
            "inputs": {
                "model": [
                    "2",
                    0,
                ],
                "lora_name": 1.0,
                "strength_model": undefined,
            },
        },
        "8": {
            "class_type": "LoraLoaderModelOnly",
            "inputs": {
                "model": [
                    "7",
                    0,
                ],
                "lora_name": 1.0,
                "strength_model": undefined,
            },
        },
        "20": {
            "class_type": "ModelSamplingAuraFlow",
            "inputs": {
                "model": [
                    "8",
                    0,
                ],
                "shift": undefined,
            },
        },
        "31": {
            "class_type": "CFGNorm",
            "inputs": {
                "model": [
                    "20",
                    0,
                ],
                "strength": 1.0,
            },
        },
        "3": {
            "class_type": "CLIPLoader",
            "inputs": {
                "clip_name": "qwen_2.5_vl_7b_fp8_scaled.safetensors",
                "type": "qwen_image",
            },
        },
        "4": {
            "class_type": "VAELoader",
            "inputs": {
                "vae_name": "qwen_image_vae.safetensors",
            },
        },
        "9": {
            "class_type": "VAEEncode",
            "inputs": {
                "pixels": [
                    "6",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "10": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "",
            },
        },
        "21": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "10",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "11": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> front view eye-level shot medium shot",
            },
        },
        "22": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "11",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "32": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "31",
                    0,
                ],
                "positive": [
                    "22",
                    0,
                ],
                "negative": [
                    "21",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "41": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "32",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "50": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "41",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "59": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "50",
                    0,
                ],
                "filename_prefix": "ComfyTV/multicam9-01-front",
            },
        },
        "12": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> front-right quarter view eye-level shot medium shot",
            },
        },
        "23": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "12",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "33": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "31",
                    0,
                ],
                "positive": [
                    "23",
                    0,
                ],
                "negative": [
                    "21",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "42": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "33",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "51": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "42",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "60": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "51",
                    0,
                ],
                "filename_prefix": "ComfyTV/multicam9-02-fr",
            },
        },
        "13": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> right side view eye-level shot medium shot",
            },
        },
        "24": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "13",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "34": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "31",
                    0,
                ],
                "positive": [
                    "24",
                    0,
                ],
                "negative": [
                    "21",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "43": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "34",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "52": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "43",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "61": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "52",
                    0,
                ],
                "filename_prefix": "ComfyTV/multicam9-03-right",
            },
        },
        "14": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> back-right quarter view eye-level shot medium shot",
            },
        },
        "25": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "14",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "35": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "31",
                    0,
                ],
                "positive": [
                    "25",
                    0,
                ],
                "negative": [
                    "21",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "44": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "35",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "53": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "44",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "62": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "53",
                    0,
                ],
                "filename_prefix": "ComfyTV/multicam9-04-br",
            },
        },
        "15": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> back view eye-level shot medium shot",
            },
        },
        "26": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "15",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "36": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "31",
                    0,
                ],
                "positive": [
                    "26",
                    0,
                ],
                "negative": [
                    "21",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "45": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "36",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "54": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "45",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "63": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "54",
                    0,
                ],
                "filename_prefix": "ComfyTV/multicam9-05-back",
            },
        },
        "16": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> back-left quarter view eye-level shot medium shot",
            },
        },
        "27": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "16",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "37": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "31",
                    0,
                ],
                "positive": [
                    "27",
                    0,
                ],
                "negative": [
                    "21",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "46": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "37",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "55": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "46",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "64": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "55",
                    0,
                ],
                "filename_prefix": "ComfyTV/multicam9-06-bl",
            },
        },
        "17": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> left side view eye-level shot medium shot",
            },
        },
        "28": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "17",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "38": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "31",
                    0,
                ],
                "positive": [
                    "28",
                    0,
                ],
                "negative": [
                    "21",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "47": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "38",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "56": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "47",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "65": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "56",
                    0,
                ],
                "filename_prefix": "ComfyTV/multicam9-07-left",
            },
        },
        "18": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> front-left quarter view eye-level shot medium shot",
            },
        },
        "29": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "18",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "39": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "31",
                    0,
                ],
                "positive": [
                    "29",
                    0,
                ],
                "negative": [
                    "21",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "48": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "39",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "57": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "48",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "66": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "57",
                    0,
                ],
                "filename_prefix": "ComfyTV/multicam9-08-fl",
            },
        },
        "19": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "3",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
                "image1": [
                    "6",
                    0,
                ],
                "prompt": "<sks> front view elevated shot medium shot",
            },
        },
        "30": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "19",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "40": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "31",
                    0,
                ],
                "positive": [
                    "30",
                    0,
                ],
                "negative": [
                    "21",
                    0,
                ],
                "latent_image": [
                    "9",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "49": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "40",
                    0,
                ],
                "vae": [
                    "4",
                    0,
                ],
            },
        },
        "58": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "49",
                    0,
                ],
                "width": [
                    "5",
                    0,
                ],
                "height": [
                    "5",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "67": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "58",
                    0,
                ],
                "filename_prefix": "ComfyTV/multicam9-09-elevated",
            },
        },
    },
    result: {
        "type": "ui_save_batch",
        "node": "59",
    },
    inputs: {
        "1": {
            "image": {
                "from": "upstream_image:annotated",
                "required": true,
                "error": "Multi-cam 9 needs an upstream image.",
            },
        },
        "11": {
            "prompt": {
                "from": "main_prompt",
                "default": "a high-quality photograph",
                "prefix": "<sks> front view eye-level shot medium shot, ",
                "required": false,
            },
        },
        "12": {
            "prompt": {
                "from": "main_prompt",
                "default": "a high-quality photograph",
                "prefix": "<sks> front-right quarter view eye-level shot medium shot, ",
                "required": false,
            },
        },
        "13": {
            "prompt": {
                "from": "main_prompt",
                "default": "a high-quality photograph",
                "prefix": "<sks> right side view eye-level shot medium shot, ",
                "required": false,
            },
        },
        "14": {
            "prompt": {
                "from": "main_prompt",
                "default": "a high-quality photograph",
                "prefix": "<sks> back-right quarter view eye-level shot medium shot, ",
                "required": false,
            },
        },
        "15": {
            "prompt": {
                "from": "main_prompt",
                "default": "a high-quality photograph",
                "prefix": "<sks> back view eye-level shot medium shot, ",
                "required": false,
            },
        },
        "16": {
            "prompt": {
                "from": "main_prompt",
                "default": "a high-quality photograph",
                "prefix": "<sks> back-left quarter view eye-level shot medium shot, ",
                "required": false,
            },
        },
        "17": {
            "prompt": {
                "from": "main_prompt",
                "default": "a high-quality photograph",
                "prefix": "<sks> left side view eye-level shot medium shot, ",
                "required": false,
            },
        },
        "18": {
            "prompt": {
                "from": "main_prompt",
                "default": "a high-quality photograph",
                "prefix": "<sks> front-left quarter view eye-level shot medium shot, ",
                "required": false,
            },
        },
        "19": {
            "prompt": {
                "from": "main_prompt",
                "default": "a high-quality photograph",
                "prefix": "<sks> front view elevated shot medium shot, ",
                "required": false,
            },
        },
        "2": {
            "unet_name": {
                "from": "literal:qwen_image_edit_2511_fp8mixed.safetensors",
                "required": false,
            },
        },
        "3": {
            "clip_name": {
                "from": "literal:qwen_2.5_vl_7b_fp8_scaled.safetensors",
                "required": false,
            },
        },
        "32": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "33": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "34": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "35": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "36": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "37": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "38": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "39": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "4": {
            "vae_name": {
                "from": "literal:qwen_image_vae.safetensors",
                "required": false,
            },
        },
        "40": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "7": {
            "lora_name": {
                "from": "literal:qwen-image-edit-2511-multiple-angles-lora.safetensors",
                "required": false,
            },
        },
        "8": {
            "lora_name": {
                "from": "literal:Qwen-Image-Edit-2511-Lightning-4steps-V1.0-bf16.safetensors",
                "required": false,
            },
        },
    },
};

export const MULTIVIEW_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "Face 3-View": MULTIVIEW_FACE_3_VIEW,
    "Product 3-View": MULTIVIEW_PRODUCT_3_VIEW,
    "Character 3-View": MULTIVIEW_CHARACTER_3_VIEW,
    "Multi-cam 9": MULTIVIEW_MULTI_CAM_9,
};
