/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const MULTIANGLE_QWEN_EDIT_2511_MULTIANGLE: StageWorkflowConfig = {
    api_json: {
        "1": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "2": {
            "class_type": "GetImageSize",
            "inputs": {
                "image": [
                    "1",
                    0,
                ],
            },
        },
        "3": {
            "class_type": "FluxKontextImageScale",
            "inputs": {
                "image": [
                    "1",
                    0,
                ],
            },
        },
        "4": {
            "class_type": "UNETLoader",
            "inputs": {
                "unet_name": "qwen_image_edit_2511_fp8mixed.safetensors",
                "weight_dtype": "default",
            },
        },
        "5": {
            "class_type": "LoraLoaderModelOnly",
            "inputs": {
                "model": [
                    "4",
                    0,
                ],
                "lora_name": 1.0,
                "strength_model": undefined,
            },
        },
        "6": {
            "class_type": "LoraLoaderModelOnly",
            "inputs": {
                "model": [
                    "5",
                    0,
                ],
                "lora_name": 1.0,
                "strength_model": undefined,
            },
        },
        "7": {
            "class_type": "ModelSamplingAuraFlow",
            "inputs": {
                "model": [
                    "6",
                    0,
                ],
                "shift": undefined,
            },
        },
        "8": {
            "class_type": "CFGNorm",
            "inputs": {
                "model": [
                    "7",
                    0,
                ],
                "strength": 1.0,
            },
        },
        "9": {
            "class_type": "CLIPLoader",
            "inputs": {
                "clip_name": "qwen_2.5_vl_7b_fp8_scaled.safetensors",
                "type": "qwen_image",
            },
        },
        "10": {
            "class_type": "VAELoader",
            "inputs": {
                "vae_name": "qwen_image_vae.safetensors",
            },
        },
        "11": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "9",
                    0,
                ],
                "vae": [
                    "10",
                    0,
                ],
                "image1": [
                    "3",
                    0,
                ],
                "prompt": "<sks> front view eye-level shot medium shot",
            },
        },
        "12": {
            "class_type": "TextEncodeQwenImageEditPlus",
            "inputs": {
                "clip": [
                    "9",
                    0,
                ],
                "vae": [
                    "10",
                    0,
                ],
                "image1": [
                    "3",
                    0,
                ],
                "prompt": "",
            },
        },
        "13": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "11",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "14": {
            "class_type": "FluxKontextMultiReferenceLatentMethod",
            "inputs": {
                "conditioning": [
                    "12",
                    0,
                ],
                "reference_latents_method": "index",
            },
        },
        "15": {
            "class_type": "VAEEncode",
            "inputs": {
                "pixels": [
                    "3",
                    0,
                ],
                "vae": [
                    "10",
                    0,
                ],
            },
        },
        "16": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "8",
                    0,
                ],
                "positive": [
                    "13",
                    0,
                ],
                "negative": [
                    "14",
                    0,
                ],
                "latent_image": [
                    "15",
                    0,
                ],
                "seed": 0,
                "steps": 4,
                "cfg": 1.0,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1.0,
            },
        },
        "17": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "16",
                    0,
                ],
                "vae": [
                    "10",
                    0,
                ],
            },
        },
        "18": {
            "class_type": "ImageScale",
            "inputs": {
                "image": [
                    "17",
                    0,
                ],
                "width": [
                    "2",
                    0,
                ],
                "height": [
                    "2",
                    1,
                ],
                "upscale_method": [
                    "source_size",
                    0,
                ],
                "crop": undefined,
            },
        },
        "19": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "18",
                    0,
                ],
                "filename_prefix": "ComfyTV/multiangle",
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "19",
    },
    inputs: {
        "1": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Multiangle needs an upstream image — wire one into the stage's image input.",
            },
        },
        "10": {
            "vae_name": {
                "from": "literal:qwen_image_vae.safetensors",
                "required": false,
            },
        },
        "11": {
            "prompt": {
                "from": "main_prompt",
                "default": "<sks> front view eye-level shot medium shot",
                "required": false,
            },
        },
        "12": {
            "prompt": {
                "from": "literal:",
                "required": false,
            },
        },
        "16": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "4": {
            "unet_name": {
                "from": "literal:qwen_image_edit_2511_fp8mixed.safetensors",
                "required": false,
            },
        },
        "5": {
            "lora_name": {
                "from": "literal:qwen-image-edit-2511-multiple-angles-lora.safetensors",
                "required": false,
            },
            "strength_model": {
                "from": "literal:1.0",
                "required": false,
                "cast": "float",
            },
        },
        "6": {
            "lora_name": {
                "from": "literal:Qwen-Image-Edit-2511-Lightning-4steps-V1.0-bf16.safetensors",
                "required": false,
            },
            "strength_model": {
                "from": "literal:1.0",
                "required": false,
                "cast": "float",
            },
        },
        "9": {
            "clip_name": {
                "from": "literal:qwen_2.5_vl_7b_fp8_scaled.safetensors",
                "required": false,
            },
        },
    },
};

export const MULTIANGLE_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "Qwen Edit 2511 Multiangle": MULTIANGLE_QWEN_EDIT_2511_MULTIANGLE,
};
