/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const OUTPAINT_FLUX_FILL_OUTPAINT: StageWorkflowConfig = {
    api_json: {
        "34": {
            "class_type": "DualCLIPLoader",
            "inputs": {
                "clip_name1": "clip_l.safetensors",
                "clip_name2": "t5xxl_fp8_e4m3fn_scaled.safetensors",
                "type": "flux",
            },
        },
        "31": {
            "class_type": "UNETLoader",
            "inputs": {
                "unet_name": "flux1-fill-dev.safetensors",
                "weight_dtype": "default",
            },
        },
        "23": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "34",
                    0,
                ],
                "text": "beautiful scenery",
            },
        },
        "32": {
            "class_type": "VAELoader",
            "inputs": {
                "vae_name": "ae.safetensors",
            },
        },
        "46": {
            "class_type": "ConditioningZeroOut",
            "inputs": {
                "conditioning": [
                    "23",
                    0,
                ],
            },
        },
        "26": {
            "class_type": "FluxGuidance",
            "inputs": {
                "conditioning": [
                    "23",
                    0,
                ],
                "guidance": 30,
            },
        },
        "39": {
            "class_type": "DifferentialDiffusion",
            "inputs": {
                "model": [
                    "31",
                    0,
                ],
            },
        },
        "44": {
            "class_type": "ImagePadForOutpaint",
            "inputs": {
                "image": [
                    "17",
                    0,
                ],
                "left": 0,
                "top": 400,
                "right": 400,
                "bottom": 24,
                "feathering": undefined,
            },
        },
        "8": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "3",
                    0,
                ],
                "vae": [
                    "32",
                    0,
                ],
            },
        },
        "38": {
            "class_type": "InpaintModelConditioning",
            "inputs": {
                "positive": [
                    "26",
                    0,
                ],
                "negative": [
                    "46",
                    0,
                ],
                "vae": [
                    "32",
                    0,
                ],
                "pixels": [
                    "44",
                    0,
                ],
                "mask": [
                    "44",
                    1,
                ],
                "noise_mask": undefined,
            },
        },
        "3": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "39",
                    0,
                ],
                "positive": [
                    "38",
                    0,
                ],
                "negative": [
                    "38",
                    1,
                ],
                "latent_image": [
                    "38",
                    2,
                ],
                "seed": 164211176398261,
                "steps": 20,
                "cfg": 1,
                "sampler_name": "euler",
                "scheduler": "normal",
                "denoise": 1,
            },
        },
        "9": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "8",
                    0,
                ],
                "filename_prefix": "ComfyUI",
            },
        },
        "17": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "flux_fill_outpaint_example_input_image.png",
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "9",
    },
    inputs: {
        "17": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Outpaint needs an upstream image — wire one into the stage's image input.",
            },
        },
        "23": {
            "text": {
                "from": "main_prompt",
                "default": "beautiful scenery",
                "required": false,
            },
        },
        "3": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "31": {
            "unet_name": {
                "from": "literal:flux1-fill-dev_fp8.safetensors",
                "required": false,
            },
        },
        "32": {
            "vae_name": {
                "from": "literal:ae.safetensors",
                "required": false,
            },
        },
        "34": {
            "clip_name1": {
                "from": "literal:clip_l.safetensors",
                "required": false,
            },
            "clip_name2": {
                "from": "literal:t5xxl_fp8_e4m3fn_scaled.safetensors",
                "required": false,
            },
        },
        "44": {
            "bottom": {
                "from": "option:pad_bottom",
                "default": 0,
                "required": false,
                "cast": "int",
            },
            "feathering": {
                "from": "option:feathering",
                "default": 40,
                "required": false,
                "cast": "int",
            },
            "left": {
                "from": "option:pad_left",
                "default": 0,
                "required": false,
                "cast": "int",
            },
            "right": {
                "from": "option:pad_right",
                "default": 0,
                "required": false,
                "cast": "int",
            },
            "top": {
                "from": "option:pad_top",
                "default": 0,
                "required": false,
                "cast": "int",
            },
        },
    },
};

export const OUTPAINT_FOOOCUS_SDXL_OUTPAINT: StageWorkflowConfig = {
    api_json: {
        "65": {
            "class_type": "ImageCompositeMasked",
            "inputs": {
                "destination": [
                    "67",
                    0,
                ],
                "source": [
                    "14",
                    0,
                ],
                "mask": [
                    "67",
                    1,
                ],
                "x": 0,
                "y": 0,
                "resize_source": false,
            },
        },
        "14": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "40",
                    0,
                ],
                "vae": [
                    "19",
                    2,
                ],
            },
        },
        "67": {
            "class_type": "ImagePadForOutpaint",
            "inputs": {
                "image": [
                    "33",
                    0,
                ],
                "left": 0,
                "top": 128,
                "right": 0,
                "bottom": 40,
                "feathering": undefined,
            },
        },
        "59": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "65",
                    0,
                ],
                "filename_prefix": "ComfyUI",
            },
        },
        "33": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "base1024.png",
            },
        },
        "19": {
            "class_type": "CheckpointLoaderSimple",
            "inputs": {
                "ckpt_name": "juggernautXL_version6Rundiffusion.safetensors",
            },
        },
        "9": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "19",
                    1,
                ],
                "text": "POSITIVE PROMPT",
            },
        },
        "10": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "19",
                    1,
                ],
                "text": "text, watermark",
            },
        },
        "40": {
            "class_type": "KSampler",
            "inputs": {
                "seed": 439968554343941,
                "steps": 28,
                "cfg": 6,
                "sampler_name": "dpmpp_2m_sde_gpu",
                "scheduler": "karras",
                "denoise": 1,
                "model": [
                    "36",
                    0,
                ],
                "positive": [
                    "44",
                    0,
                ],
                "negative": [
                    "44",
                    1,
                ],
                "latent_image": [
                    "44",
                    3,
                ],
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "59",
    },
    inputs: {
        "10": {
            "text": {
                "from": "option:negative",
                "default": "text, watermark, low quality, blurry",
                "required": false,
            },
        },
        "19": {
            "ckpt_name": {
                "from": "literal:animagine-xl-3.1.safetensors",
                "required": false,
            },
        },
        "33": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Outpaint needs an upstream image — wire one into the stage's image input.",
            },
        },
        "40": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "67": {
            "bottom": {
                "from": "option:pad_bottom",
                "default": 0,
                "required": false,
                "cast": "int",
            },
            "feathering": {
                "from": "option:feathering",
                "default": 40,
                "required": false,
                "cast": "int",
            },
            "left": {
                "from": "option:pad_left",
                "default": 0,
                "required": false,
                "cast": "int",
            },
            "right": {
                "from": "option:pad_right",
                "default": 0,
                "required": false,
                "cast": "int",
            },
            "top": {
                "from": "option:pad_top",
                "default": 0,
                "required": false,
                "cast": "int",
            },
        },
        "9": {
            "text": {
                "from": "main_prompt",
                "default": "natural continuation of the scene, seamless",
                "required": false,
            },
        },
    },
};

export const OUTPAINT_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "Flux Fill Outpaint": OUTPAINT_FLUX_FILL_OUTPAINT,
    "Fooocus SDXL Outpaint": OUTPAINT_FOOOCUS_SDXL_OUTPAINT,
};
