/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const PANORAMA_QWEN_IMAGE_2512_360_LORA: StageWorkflowConfig = {
    api_json: {
        "60": {
            "class_type": "SaveImage",
            "inputs": {
                "filename_prefix": "Qwen-Image-2512",
                "images": [
                    "238",
                    0,
                ],
            },
        },
        "266": {
            "class_type": "PrimitiveStringMultiline",
            "inputs": {
                "value": "equirectangular 360 image, ",
            },
        },
        "267": {
            "class_type": "StringConcatenate",
            "inputs": {
                "string_a": [
                    "266",
                    0,
                ],
                "string_b": [
                    "269",
                    0,
                ],
                "delimiter": "",
            },
        },
        "269": {
            "class_type": "PrimitiveStringMultiline",
            "inputs": {
                "value": "A spacious warm living room, soft sunlight through window, soft sofa, delicate decor, green potted plants, clean tidy space, gentle ambient light",
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "60",
    },
    inputs: {
        "266": {
            "value": {
                "from": "literal:",
                "required": false,
            },
        },
        "269": {
            "value": {
                "from": "main_prompt",
                "default": "equirectangular 360 degree panorama, a peaceful landscape",
                "required": false,
            },
        },
    },
};

export const PANORAMA_QWEN_IMAGE_EDIT_2511_IMAGE_TO_PANORAMA: StageWorkflowConfig = {
    api_json: {
        "41": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "leather_sofa.png",
            },
        },
        "9": {
            "class_type": "SaveImage",
            "inputs": {
                "filename_prefix": "Qwen_Edit_2511",
                "images": [
                    "170",
                    0,
                ],
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "9",
    },
    inputs: {
        "41": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Image-to-Panorama needs an upstream image — wire a regular wide-angle photo into the stage's image input.",
            },
        },
    },
};

export const PANORAMA_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "Qwen-Image 2512 + 360 LoRA": PANORAMA_QWEN_IMAGE_2512_360_LORA,
    "Qwen-Image-Edit 2511 Image-to-Panorama": PANORAMA_QWEN_IMAGE_EDIT_2511_IMAGE_TO_PANORAMA,
};
