/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const SHOT_IMAGES_Z_IMAGE_TURBO_PER_SHOT: StageWorkflowConfig = {
    api_json: {
        "9": {
            "class_type": "SaveImage",
            "inputs": {
                "filename_prefix": "z-image-turbo",
                "images": [
                    "57",
                    0,
                ],
            },
        },
    },
    result: undefined,
    inputs: {},
};

export const SHOT_IMAGES_FLUX_SCHNELL_PER_SHOT: StageWorkflowConfig = {
    api_json: {
        "33": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "30",
                    1,
                ],
                "text": "",
            },
        },
        "27": {
            "class_type": "EmptySD3LatentImage",
            "inputs": {
                "width": 1024,
                "height": 1024,
                "batch_size": 1,
            },
        },
        "8": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "31",
                    0,
                ],
                "vae": [
                    "30",
                    2,
                ],
            },
        },
        "9": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "8",
                    0,
                ],
                "filename_prefix": "ComfyUI",
            },
        },
        "31": {
            "class_type": "KSampler",
            "inputs": {
                "model": [
                    "30",
                    0,
                ],
                "positive": [
                    "6",
                    0,
                ],
                "negative": [
                    "33",
                    0,
                ],
                "latent_image": [
                    "27",
                    0,
                ],
                "seed": 173805153958730,
                "steps": 4,
                "cfg": 1,
                "sampler_name": "euler",
                "scheduler": "simple",
                "denoise": 1,
            },
        },
        "30": {
            "class_type": "CheckpointLoaderSimple",
            "inputs": {
                "ckpt_name": "flux1-schnell-fp8.safetensors",
            },
        },
        "6": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "30",
                    1,
                ],
                "text": "a bottle with a beautiful rainbow galaxy inside it on top of a wooden table in the middle of a modern kitchen beside a plate of vegetables and mushrooms and a wine glasse that contains a planet earth with a plate with a half eaten apple pie on it",
            },
        },
    },
    result: undefined,
    inputs: {
        "27": {
            "batch_size": {
                "from": "literal:1",
                "required": false,
                "cast": "int",
            },
            "height": {
                "from": "computed:height",
                "required": false,
            },
            "width": {
                "from": "computed:width",
                "required": false,
            },
        },
        "30": {
            "ckpt_name": {
                "from": "literal:flux1-schnell-fp8.safetensors",
                "required": false,
            },
        },
        "31": {
            "seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "6": {
            "text": {
                "from": "main_prompt",
                "default": "a photograph",
                "required": false,
            },
        },
    },
};

export const SHOT_IMAGES_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "Z-Image Turbo (per-shot)": SHOT_IMAGES_Z_IMAGE_TURBO_PER_SHOT,
    "Flux Schnell (per-shot)": SHOT_IMAGES_FLUX_SCHNELL_PER_SHOT,
};
