/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const SPLIT_PART_SAM3_POINTS_BOXES: StageWorkflowConfig = {
    api_json: {
        "1": {
            "class_type": "CheckpointLoaderSimple",
            "inputs": {
                "ckpt_name": "sam3.1_multiplex_fp16.safetensors",
            },
        },
        "2": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "10": {
            "class_type": "ComfyTV.MaskCleanup",
            "inputs": {
                "min_region_frac": 0.01,
                "mask": [
                    "3",
                    0,
                ],
            },
        },
        "4": {
            "class_type": "InvertMask",
            "inputs": {
                "mask": [
                    "10",
                    0,
                ],
            },
        },
        "5": {
            "class_type": "JoinImageWithAlpha",
            "inputs": {
                "image": [
                    "2",
                    0,
                ],
                "alpha": [
                    "4",
                    0,
                ],
            },
        },
        "9": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "5",
                    0,
                ],
                "filename_prefix": "comfytv-part",
            },
        },
    },
    result: {
        "type": "ui_save_batch",
        "node": "9",
    },
    inputs: {
        "2": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Split Parts needs an upstream image — wire one into the stage's image input.",
            },
        },
    },
};

export const SPLIT_PART_SAM3_TEXT_CONCEPT: StageWorkflowConfig = {
    api_json: {
        "1": {
            "class_type": "CheckpointLoaderSimple",
            "inputs": {
                "ckpt_name": "sam3.1_multiplex_fp16.safetensors",
            },
        },
        "2": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "6": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": [
                    "1",
                    1,
                ],
                "text": "",
            },
        },
        "10": {
            "class_type": "ComfyTV.MaskCleanup",
            "inputs": {
                "min_region_frac": 0.01,
                "mask": [
                    "3",
                    0,
                ],
            },
        },
        "4": {
            "class_type": "InvertMask",
            "inputs": {
                "mask": [
                    "10",
                    0,
                ],
            },
        },
        "5": {
            "class_type": "JoinImageWithAlpha",
            "inputs": {
                "image": [
                    "2",
                    0,
                ],
                "alpha": [
                    "4",
                    0,
                ],
            },
        },
        "9": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "5",
                    0,
                ],
                "filename_prefix": "comfytv-part",
            },
        },
    },
    result: {
        "type": "ui_save_batch",
        "node": "9",
    },
    inputs: {
        "2": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Split Parts needs an upstream image — wire one into the stage's image input.",
            },
        },
        "6": {
            "text": {
                "from": "main_prompt",
                "required": true,
                "error": "The text workflow needs a concept prompt — type what to segment (e.g. 'strap').",
            },
        },
    },
};

export const SPLIT_PART_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "SAM3 Points & Boxes": SPLIT_PART_SAM3_POINTS_BOXES,
    "SAM3 Text Concept": SPLIT_PART_SAM3_TEXT_CONCEPT,
};
