/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const STORYBOARD_LOCAL_QWEN3_4B_STORYBOARD: StageWorkflowConfig = {
    api_json: {
        "7": {
            "class_type": "TextGenerate",
            "inputs": {
                "clip": [
                    "8",
                    0,
                ],
                "prompt": "Now ComfyUI has native LLM support, and you can use Qwen2.5 and Qwen3.0 series models",
                "max_length": 2048,
            },
        },
        "5": {
            "class_type": "PreviewAny",
            "inputs": {
                "source": [
                    "7",
                    0,
                ],
            },
        },
        "8": {
            "class_type": "CLIPLoader",
            "inputs": {
                "clip_name": "qwen_3_4b.safetensors",
                "type": "ltxv",
            },
        },
    },
    result: {
        "type": "graph_output_first",
        "node": "7",
    },
    inputs: {
        "7": {
            "max_length": {
                "from": "option:max_length",
                "default": 6144,
                "required": false,
                "cast": "int",
            },
            "prompt": {
                "from": "main_prompt",
                "default": "Hello.",
                "required": false,
            },
            "use_default_template": {
                "from": "literal:false",
                "required": false,
                "cast": "bool",
            },
        },
    },
};

export const STORYBOARD_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "Local Qwen3 4B Storyboard": STORYBOARD_LOCAL_QWEN3_4B_STORYBOARD,
};
