/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const TEXT_LOCAL_QWEN3_4B: StageWorkflowConfig = {
    api_json: {
        "7": {
            "class_type": "TextGenerate",
            "inputs": {
                "clip": [
                    "8",
                    0,
                ],
                "prompt": "Now ComfyUI has native LLM support, and you can use Qwen2.5 and Qwen3.0 series models",
                "max_length": 2048,
            },
        },
        "5": {
            "class_type": "PreviewAny",
            "inputs": {
                "source": [
                    "7",
                    0,
                ],
            },
        },
        "8": {
            "class_type": "CLIPLoader",
            "inputs": {
                "clip_name": "qwen_3_4b.safetensors",
                "type": "ltxv",
            },
        },
    },
    result: {
        "type": "graph_output_first",
        "node": "7",
    },
    inputs: {
        "7": {
            "prompt": {
                "from": "main_prompt",
                "default": "Hello.",
                "required": false,
            },
        },
    },
};

export const TEXT_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "Local Qwen3 4B": TEXT_LOCAL_QWEN3_4B,
};
