/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const UPSCALE_ULTRASHARP_4X: StageWorkflowConfig = {
    api_json: {
        "1": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "2": {
            "class_type": "UpscaleModelLoader",
            "inputs": {
                "model_name": "4x-UltraSharp.pth",
            },
        },
        "3": {
            "class_type": "ImageUpscaleWithModel",
            "inputs": {
                "upscale_model": [
                    "2",
                    0,
                ],
                "image": [
                    "1",
                    0,
                ],
            },
        },
        "4": {
            "class_type": "SaveImage",
            "inputs": {
                "images": [
                    "3",
                    0,
                ],
                "filename_prefix": "ComfyUI",
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "4",
    },
    inputs: {
        "1": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "Upscale needs an upstream image — wire one into this stage's image input.",
            },
        },
        "2": {
            "model_name": {
                "from": "literal:4x-UltraSharp.pth",
                "required": false,
            },
        },
    },
};

export const UPSCALE_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "Ultrasharp 4x": UPSCALE_ULTRASHARP_4X,
};
