/*---------------------------------------------------------------------------------------------
 *  AUTO-GENERATED by scripts/export-builtin-workflows.py — DO NOT EDIT.
 *  数据源: D:\ComfyUI\user\comfytv\data.db（comfytv_workflows + comfytv_workflow_input_bindings）
 *  重新运行脚本可覆盖此文件。
 *--------------------------------------------------------------------------------------------*/

import type { StageWorkflowConfig } from '../stageWorkflowExecutor.js';


export const VIDEO_LOCAL_LTX_2_3_T2V: StageWorkflowConfig = {
    api_json: {
        "75": {
            "class_type": "SaveVideo",
            "inputs": {
                "filename_prefix": "video/LTX_2.3_t2v",
                "format": "auto",
                "codec": "auto",
                "video": [
                    "267",
                    0,
                ],
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "75",
    },
    inputs: {},
};

export const VIDEO_LOCAL_LTX_2_3_I2V: StageWorkflowConfig = {
    api_json: {
        "269": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "egyptian_queen.png",
            },
        },
        "75": {
            "class_type": "SaveVideo",
            "inputs": {
                "filename_prefix": "video/LTX_2.3_i2v",
                "format": "auto",
                "codec": "auto",
                "video": [
                    "320",
                    0,
                ],
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "75",
    },
    inputs: {
        "269": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "LTX 2.3 I2V needs an upstream image — wire one into the stage's images slot, or pick Local LTX 2.3 T2V for pure text-to-video.",
            },
        },
    },
};

export const VIDEO_LOCAL_LTX_2_3_FLF2V: StageWorkflowConfig = {
    api_json: {
        "39": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "low_view_classic_car.png",
            },
        },
        "68": {
            "class_type": "SaveVideo",
            "inputs": {
                "filename_prefix": "video/ltx2.3_flf2v",
                "format": "auto",
                "codec": "auto",
                "video": [
                    "129",
                    0,
                ],
            },
        },
        "31": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "high_view_classic_car.png",
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "68",
    },
    inputs: {
        "31": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "FLF2V needs a FIRST-frame image — wire one into the stage's images.image0 slot.",
            },
        },
        "39": {
            "image": {
                "from": "upstream_image:annotated[1]",
                "required": true,
                "error": "FLF2V needs a LAST-frame image — wire a second image into the stage's images.image1 slot.",
            },
        },
    },
};

export const VIDEO_LOCAL_LTX_2_3_IA2V: StageWorkflowConfig = {
    api_json: {
        "269": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "cactus_man.png",
            },
        },
        "339": {
            "class_type": "RecordAudio",
            "inputs": {},
        },
        "341": {
            "class_type": "SaveVideo",
            "inputs": {
                "filename_prefix": "video/LTX_2.3_ia2v",
                "format": "auto",
                "codec": "auto",
                "video": [
                    "340",
                    0,
                ],
            },
        },
        "276": {
            "class_type": "LoadAudio",
            "inputs": {
                "audio": "ltx_23_audio.mp3",
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "341",
    },
    inputs: {
        "269": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "LTX 2.3 IA2V needs an upstream image — wire one into the stage's images slot.",
            },
        },
        "276": {
            "audio": {
                "from": "upstream_audio:annotated[0]",
                "required": true,
                "error": "LTX 2.3 IA2V needs an audio track — wire one into the stage's audio socket (try an AudioStage).",
            },
        },
    },
};

export const VIDEO_LOCAL_MINIMAX_H3_R2V: StageWorkflowConfig = {
    api_json: {
        "92": {
            "class_type": "SaveVideo",
            "inputs": {
                "video": [
                    "130",
                    0,
                ],
                "filename_prefix": "video/MiniMax_H3",
                "format": "auto",
                "codec": "auto",
            },
        },
        "119": {
            "class_type": "VAELoader",
            "inputs": {
                "vae_name": "minimax_h3_video_vae_fp16.safetensors",
            },
        },
        "120": {
            "class_type": "VAELoader",
            "inputs": {
                "vae_name": "minimax_h3_audio_vae_fp32.safetensors",
            },
        },
        "121": {
            "class_type": "VAEDecodeAudio",
            "inputs": {
                "samples": [
                    "125",
                    0,
                ],
                "vae": [
                    "120",
                    0,
                ],
            },
        },
        "122": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "125",
                    0,
                ],
                "vae": [
                    "119",
                    0,
                ],
            },
        },
        "123": {
            "class_type": "KSamplerSelect",
            "inputs": {
                "sampler_name": "res_multistep",
            },
        },
        "124": {
            "class_type": "BasicScheduler",
            "inputs": {
                "model": [
                    "127",
                    0,
                ],
                "scheduler": "simple",
                "steps": 20,
                "denoise": 1,
            },
        },
        "125": {
            "class_type": "SamplerCustomAdvanced",
            "inputs": {
                "noise": [
                    "129",
                    0,
                ],
                "guider": [
                    "126",
                    0,
                ],
                "sampler": [
                    "123",
                    0,
                ],
                "sigmas": [
                    "124",
                    0,
                ],
                "latent_image": [
                    "136",
                    1,
                ],
            },
        },
        "126": {
            "class_type": "BasicGuider",
            "inputs": {
                "model": [
                    "127",
                    0,
                ],
                "conditioning": [
                    "136",
                    0,
                ],
            },
        },
        "127": {
            "class_type": "UNETLoader",
            "inputs": {
                "unet_name": "minimax_h3_ref2va_pruned_int8_convrot.safetensors",
                "weight_dtype": "default",
            },
        },
        "128": {
            "class_type": "CLIPLoader",
            "inputs": {
                "clip_name": "qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors",
                "type": "minimax",
            },
        },
        "129": {
            "class_type": "RandomNoise",
            "inputs": {
                "noise_seed": 157368968253448,
            },
        },
        "130": {
            "class_type": "CreateVideo",
            "inputs": {
                "images": [
                    "122",
                    0,
                ],
                "audio": [
                    "121",
                    0,
                ],
                "fps": 24,
            },
        },
        "131": {
            "class_type": "ComfyMathExpression",
            "inputs": {
                "values.a": [
                    "132",
                    0,
                ],
                "expression": "max(5, round(a * 24)) + (5 - (max(5, round(a * 24)) % 17)) % 17",
            },
        },
        "132": {
            "class_type": "PrimitiveFloat",
            "inputs": {
                "value": 5,
            },
        },
        "137": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "red_superboy_on_city_roof.png",
            },
        },
        "138": {
            "class_type": "PrimitiveStringMultiline",
            "inputs": {
                "value": "Bold comic-book ink style, heavy linework, red and blue-black palette, night city. Use <Picture 2> and <Picture 1> as reference frames and <Audio 1> exactly as it is.\nCUT 1: top-down view of the little boy superhero on the rooftop — red cape fluttering in the wind, hands planted on his hips, freckles and a cocky grin as he looks straight up into the camera. The camera slowly descends toward him as he delivers his line — as he speaks, comic-book graphic overlay text word by word in sync with his voice: \"GET READY TO\" - \"MEET\" — \"YOUR\" — \"MAKER\" — huge jagged comic lettering, white with heavy black outlines and red drop shadows, tilted at scrappy angles, until the three words hang stacked in the air above him between his face and the lens.\nTRANSITION: a violent WHIP PAN off the rooftop that SMEARS the floating words away with it, motion-streaked —\nCUT 2: low hero angle on the colossal black mech-kaiju towering over the skyline as it rears back and unleashes a GIANT terrifying ROAR — jaws wide with fangs, red eyes and chest-core flaring blinding bright, blue lightning arcing off its head, the roar's shockwave rippling dust and rattling windows down the buildings, comic-style speed-lines and ink splatter bursting from the impact of the sound. It leans INTO the camera as the roar peaks. Hold on the roar.",
            },
        },
        "139": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "mecha_dragon_lightning.png",
            },
        },
        "201": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "202": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "203": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "204": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "205": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "206": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "207": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
        "301": {
            "class_type": "LoadVideo",
            "inputs": {
                "file": "example.mp4",
            },
        },
        "302": {
            "class_type": "GetVideoComponents",
            "inputs": {
                "video": [
                    "301",
                    0,
                ],
            },
        },
        "303": {
            "class_type": "LoadVideo",
            "inputs": {
                "file": "example.mp4",
            },
        },
        "304": {
            "class_type": "GetVideoComponents",
            "inputs": {
                "video": [
                    "303",
                    0,
                ],
            },
        },
        "401": {
            "class_type": "LoadAudio",
            "inputs": {
                "audio": "example.mp3",
            },
        },
        "402": {
            "class_type": "LoadAudio",
            "inputs": {
                "audio": "example.mp3",
            },
        },
        "403": {
            "class_type": "LoadAudio",
            "inputs": {
                "audio": "example.mp3",
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "92",
    },
    inputs: {
        "129": {
            "noise_seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "132": {
            "value": {
                "from": "option:duration_s",
                "required": false,
                "cast": "float",
            },
        },
        "137": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": false,
            },
        },
        "138": {
            "value": {
                "from": "main_prompt",
                "required": true,
                "error": "MiniMax H3 needs a prompt.",
            },
        },
        "139": {
            "image": {
                "from": "upstream_image:annotated[1]",
                "required": false,
            },
        },
        "201": {
            "image": {
                "from": "upstream_image:annotated[2]",
                "required": false,
            },
        },
        "202": {
            "image": {
                "from": "upstream_image:annotated[3]",
                "required": false,
            },
        },
        "203": {
            "image": {
                "from": "upstream_image:annotated[4]",
                "required": false,
            },
        },
        "204": {
            "image": {
                "from": "upstream_image:annotated[5]",
                "required": false,
            },
        },
        "205": {
            "image": {
                "from": "upstream_image:annotated[6]",
                "required": false,
            },
        },
        "206": {
            "image": {
                "from": "upstream_image:annotated[7]",
                "required": false,
            },
        },
        "207": {
            "image": {
                "from": "upstream_image:annotated[8]",
                "required": false,
            },
        },
        "301": {
            "file": {
                "from": "upstream_video:annotated[0]",
                "required": false,
            },
        },
        "303": {
            "file": {
                "from": "upstream_video:annotated[1]",
                "required": false,
            },
        },
        "401": {
            "audio": {
                "from": "upstream_audio:annotated[0]",
                "required": false,
            },
        },
        "402": {
            "audio": {
                "from": "upstream_audio:annotated[1]",
                "required": false,
            },
        },
        "403": {
            "audio": {
                "from": "upstream_audio:annotated[2]",
                "required": false,
            },
        },
    },
};

export const VIDEO_LOCAL_MINIMAX_H3_T2V: StageWorkflowConfig = {
    api_json: {
        "92": {
            "class_type": "SaveVideo",
            "inputs": {
                "video": [
                    "130",
                    0,
                ],
                "filename_prefix": "video/MiniMax_H3",
                "format": "auto",
                "codec": "auto",
            },
        },
        "119": {
            "class_type": "VAELoader",
            "inputs": {
                "vae_name": "minimax_h3_video_vae_fp16.safetensors",
            },
        },
        "120": {
            "class_type": "VAELoader",
            "inputs": {
                "vae_name": "minimax_h3_audio_vae_fp32.safetensors",
            },
        },
        "121": {
            "class_type": "VAEDecodeAudio",
            "inputs": {
                "samples": [
                    "125",
                    0,
                ],
                "vae": [
                    "120",
                    0,
                ],
            },
        },
        "122": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": [
                    "125",
                    0,
                ],
                "vae": [
                    "119",
                    0,
                ],
            },
        },
        "123": {
            "class_type": "KSamplerSelect",
            "inputs": {
                "sampler_name": "res_multistep",
            },
        },
        "124": {
            "class_type": "BasicScheduler",
            "inputs": {
                "model": [
                    "127",
                    0,
                ],
                "scheduler": "simple",
                "steps": 20,
                "denoise": 1,
            },
        },
        "125": {
            "class_type": "SamplerCustomAdvanced",
            "inputs": {
                "noise": [
                    "129",
                    0,
                ],
                "guider": [
                    "126",
                    0,
                ],
                "sampler": [
                    "123",
                    0,
                ],
                "sigmas": [
                    "124",
                    0,
                ],
                "latent_image": [
                    "131",
                    1,
                ],
            },
        },
        "126": {
            "class_type": "BasicGuider",
            "inputs": {
                "model": [
                    "127",
                    0,
                ],
                "conditioning": [
                    "131",
                    0,
                ],
            },
        },
        "127": {
            "class_type": "UNETLoader",
            "inputs": {
                "unet_name": "minimax_h3_fl2va_pruned_int8_convrot.safetensors",
                "weight_dtype": "default",
            },
        },
        "128": {
            "class_type": "CLIPLoader",
            "inputs": {
                "clip_name": "qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors",
                "type": "minimax",
            },
        },
        "129": {
            "class_type": "RandomNoise",
            "inputs": {
                "noise_seed": 1,
            },
        },
        "130": {
            "class_type": "CreateVideo",
            "inputs": {
                "images": [
                    "122",
                    0,
                ],
                "audio": [
                    "121",
                    0,
                ],
                "fps": 24,
            },
        },
        "132": {
            "class_type": "ComfyMathExpression",
            "inputs": {
                "values.a": [
                    "133",
                    0,
                ],
                "expression": "max(5, round(a * 24)) + (5 - (max(5, round(a * 24)) % 17)) % 17",
            },
        },
        "133": {
            "class_type": "PrimitiveFloat",
            "inputs": {
                "value": 2,
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "92",
    },
    inputs: {
        "129": {
            "noise_seed": {
                "from": "option:seed",
                "default": "random_int31",
                "required": false,
                "cast": "int",
            },
        },
        "133": {
            "value": {
                "from": "option:duration_s",
                "required": false,
                "cast": "float",
            },
        },
    },
};

export const VIDEO_LOCAL_MINIMAX_H3_FLF2V: StageWorkflowConfig = {
    api_json: {
        "92": {
            "class_type": "SaveVideo",
            "inputs": {
                "filename_prefix": "video/MiniMax_H3",
                "format": "auto",
                "codec": "auto",
                "video": [
                    "105",
                    0,
                ],
            },
        },
        "114": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "transparent_rgb_gaming_mouse.png",
            },
        },
        "119": {
            "class_type": "ImageScaleToTotalPixels",
            "inputs": {
                "upscale_method": "nearest-exact",
                "megapixels": 1,
                "resolution_steps": 32,
            },
        },
        "120": {
            "class_type": "GetImageSize",
            "inputs": {
                "image": [
                    "119",
                    0,
                ],
            },
        },
        "200": {
            "class_type": "LoadImage",
            "inputs": {
                "image": "example.png",
            },
        },
    },
    result: {
        "type": "ui_save_url",
        "node": "92",
    },
    inputs: {
        "114": {
            "image": {
                "from": "upstream_image:annotated[0]",
                "required": true,
                "error": "MiniMax H3 FLF2V needs at least a first-frame image — wire one into the stage's first image slot.",
            },
        },
        "200": {
            "image": {
                "from": "upstream_image:annotated[1]",
                "required": false,
            },
        },
    },
};

export const VIDEO_BUILTIN_WORKFLOWS: Record<string, StageWorkflowConfig> = {
    "Local LTX 2.3 T2V": VIDEO_LOCAL_LTX_2_3_T2V,
    "Local LTX 2.3 I2V": VIDEO_LOCAL_LTX_2_3_I2V,
    "Local LTX 2.3 FLF2V": VIDEO_LOCAL_LTX_2_3_FLF2V,
    "Local LTX 2.3 IA2V": VIDEO_LOCAL_LTX_2_3_IA2V,
    "Local MiniMax H3 R2V": VIDEO_LOCAL_MINIMAX_H3_R2V,
    "Local MiniMax H3 T2V": VIDEO_LOCAL_MINIMAX_H3_T2V,
    "Local MiniMax H3 FLF2V": VIDEO_LOCAL_MINIMAX_H3_FLF2V,
};
